import {BadRequestException,Inject,Injectable,UnauthorizedException} from '@nestjs/common';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import {PrismaService} from '../common/prisma.service';
import {hashToken,secretToken} from '../common/security';
import {EmailService} from '../communications/email.service';
import {Response} from 'express';
@Injectable()
export class AuthService {
 constructor(@Inject(PrismaService) private db:PrismaService,@Inject(EmailService) private email:EmailService){}
 async publicUser(id:string){const u=await this.db.user.findUniqueOrThrow({where:{id},include:{role:true}});return{id:u.id,email:u.email,name:u.name,kind:u.kind,verified:u.verified,permissions:u.role?.permissions||[]};}
 cookies(res:Response,access:string,refresh:string){const options={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/'};res.cookie('access_token',access,{...options,maxAge:15*60*1000});res.cookie('refresh_token',refresh,{...options,maxAge:30*86400*1000});}
 clear(res:Response){for(const name of ['access_token','refresh_token'])res.clearCookie(name,{path:'/',httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax'});}
 async issue(userId:string,res:Response){const token=secretToken();const session=await this.db.session.create({data:{userId,tokenHash:hashToken(token),expiresAt:new Date(Date.now()+30*86400*1000)}});const access=jwt.sign({sid:session.id},process.env.JWT_SECRET!,{subject:userId,expiresIn:'15m',algorithm:'HS256'});this.cookies(res,access,token);return this.publicUser(userId);}
 async register(input:{email:string;name:string;password:string},res:Response){if(await this.db.user.findUnique({where:{email:input.email}}))throw new BadRequestException('An account with this email already exists');const u=await this.db.user.create({data:{email:input.email,name:input.name,passwordHash:await bcrypt.hash(input.password,12)}});await this.sendToken(u.id,'VERIFY');return this.issue(u.id,res);}
 async login(input:{email:string;password:string},res:Response){const user=await this.db.user.findUnique({where:{email:input.email}});const valid=await bcrypt.compare(input.password,user?.passwordHash||'$2b$12$MQhUrdvULjOIuoSKjqWFhO/pBoZdG20yQBsz0RXUvRnoGlBIRh9Ly');if(!user||!valid||!user.active)throw new UnauthorizedException('Email or password is incorrect');return this.issue(user.id,res);}
 async refresh(token:string|undefined,res:Response){if(!token)throw new UnauthorizedException();const newToken=secretToken();const result=await this.db.$transaction(async tx=>{const session=await tx.session.findUnique({where:{tokenHash:hashToken(token)},include:{user:true}});if(!session||session.revokedAt||session.expiresAt<new Date()||!session.user.active)throw new UnauthorizedException('Session expired');const claimed=await tx.session.updateMany({where:{id:session.id,revokedAt:null},data:{revokedAt:new Date()}});if(!claimed.count)throw new UnauthorizedException('Session already rotated');return tx.session.create({data:{userId:session.userId,tokenHash:hashToken(newToken),expiresAt:new Date(Date.now()+30*86400*1000)}});});this.cookies(res,jwt.sign({sid:result.id},process.env.JWT_SECRET!,{subject:result.userId,expiresIn:'15m',algorithm:'HS256'}),newToken);return this.publicUser(result.userId);}
 async logout(token:string|undefined,res:Response){if(token)await this.db.session.updateMany({where:{tokenHash:hashToken(token)},data:{revokedAt:new Date()}});this.clear(res);return{message:'Signed out'};}
 async sendToken(userId:string,kind:'VERIFY'|'RESET'){const user=await this.db.user.findUniqueOrThrow({where:{id:userId}});const token=secretToken();await this.db.authToken.create({data:{userId,kind,tokenHash:hashToken(token),expiresAt:new Date(Date.now()+(kind==='VERIFY'?86400000:3600000))}});const url=`${process.env.APP_URL}/account?${kind==='VERIFY'?'verify':'reset'}=${token}`;await this.email.enqueue(user.email,kind==='VERIFY'?'verify_email':'password_reset',{name:user.name,url,message:`Use this secure link: ${url}`});}
 async forgot(email:string){const user=await this.db.user.findUnique({where:{email}});if(user?.active)await this.sendToken(user.id,'RESET');return{message:'If an account exists, a reset link has been sent.'};}
 async redeem(token:string,kind:'VERIFY'|'RESET',password?:string){const passwordHash=password?await bcrypt.hash(password,12):undefined;await this.db.$transaction(async tx=>{const record=await tx.authToken.findUnique({where:{tokenHash:hashToken(token)}});if(!record||record.kind!==kind||record.usedAt||record.expiresAt<new Date())throw new BadRequestException('This link is invalid or expired');const used=await tx.authToken.updateMany({where:{id:record.id,usedAt:null},data:{usedAt:new Date()}});if(!used.count)throw new BadRequestException('This link has already been used');await tx.user.update({where:{id:record.userId},data:kind==='VERIFY'?{verified:true}:{passwordHash}});if(kind==='RESET')await tx.session.updateMany({where:{userId:record.userId},data:{revokedAt:new Date()}});});return{message:kind==='VERIFY'?'Email verified':'Password updated. Please sign in.'};}
}
