import {BadRequestException,ConflictException,Inject,Injectable,ServiceUnavailableException} from '@nestjs/common';
import {Prisma} from '@prisma/client';
import {createHmac,randomUUID} from 'node:crypto';
import {CheckoutInput} from '@vanta/types';
import {PrismaService} from '../common/prisma.service';
import {hashToken,Principal} from '../common/security';
import {calculateCoupon,calculateTax,mergeQuantities} from './rules';
import {activeWindow,discountedPrice} from '../catalog/catalog.service';
import {orderInclude,orderView} from './order-view';
import {PaymentService} from './payment.service';
import {EmailService} from '../communications/email.service';
export function couponOrderWhere(user:{id:string;email:string}|undefined,contactEmail:string,couponId:string,firstOrderOnly:boolean):Prisma.OrderWhereInput {const identity=user?{OR:[{userId:user.id},{userId:null,email:user.email.toLowerCase()}]}:{email:contactEmail.toLowerCase()};return{status:{not:'CANCELLED'},...(!firstOrderOnly?{couponId}:{}),...identity};}
@Injectable()
export class CheckoutService {
 constructor(@Inject(PrismaService) private db:PrismaService,@Inject(PaymentService) private payments:PaymentService,@Inject(EmailService) private email:EmailService){}
 async calculate(tx:Prisma.TransactionClient,input:CheckoutInput,user?:Principal){
  const merged=mergeQuantities(input.items);if(merged.some(x=>x.quantity>50))throw new BadRequestException('A maximum of 50 units per variant is allowed');
  const variants=await tx.productVariant.findMany({where:{id:{in:merged.map(i=>i.variantId)}},include:{inventory:true,product:{include:{images:{orderBy:{position:'asc'}},collections:true}}}});if(variants.length!==merged.length)throw new BadRequestException('A product is unavailable');
  const now=new Date();const discounts=await tx.discount.findMany({where:{active:true,AND:[{OR:[{startsAt:null},{startsAt:{lte:now}}]},{OR:[{endsAt:null},{endsAt:{gt:now}}]},{OR:[{campaignId:null},{campaign:{status:{in:['ACTIVE','SCHEDULED']},startsAt:{lte:now},endsAt:{gt:now}}}]}]}});
  const lines=merged.map(item=>{const variant=variants.find(v=>v.id===item.variantId)!;const product=variant.product;if(!variant.active||product.status!=='ACTIVE'||!product.visibility)throw new BadRequestException('Product unavailable');const available=variant.inventory.reduce((s,i)=>s+i.quantity-i.reserved,0);if(item.quantity>available)throw new ConflictException(`Insufficient stock for ${product.name} / ${variant.size}`);const base=variant.salePrice??variant.price??product.salePrice??product.price;return{...item,variant,product,productId:product.id,categoryId:product.categoryId,collectionIds:product.collections.map(c=>c.collectionId),price:discountedPrice(base,product,discounts)};});
  const subtotal=lines.reduce((s,l)=>s+l.price*l.quantity,0);let discount=0,freeShipping=false;
  const coupon=input.couponCode?await tx.coupon.findUnique({where:{code:input.couponCode.toUpperCase()}}):null;
  if(input.couponCode){if(!coupon||!coupon.active||!activeWindow(coupon.startsAt,coupon.endsAt))throw new BadRequestException('Coupon is invalid or expired');if(coupon.usageLimit!==null&&coupon.usedCount>=coupon.usageLimit)throw new BadRequestException('Coupon usage limit reached');const couponEmail=(user?.email||input.email).toLowerCase();if(coupon.customerEmails.length&&!coupon.customerEmails.map(email=>email.toLowerCase()).includes(couponEmail))throw new BadRequestException('Coupon is not available for this customer');const previous=await tx.order.count({where:couponOrderWhere(user,input.email,coupon.id,coupon.firstOrderOnly)});if((coupon.firstOrderOnly&&previous>0)||(!coupon.firstOrderOnly&&previous>=coupon.perCustomerLimit))throw new BadRequestException('Coupon already used');try{({discount,freeShipping}=calculateCoupon(coupon,lines));}catch(e){throw new BadRequestException(e instanceof Error?e.message:'Coupon unavailable');}}
  const method=await tx.shippingMethod.findUnique({where:{id:input.shippingMethodId}});const weight=lines.reduce((s,l)=>s+l.variant.weight*l.quantity,0);if(!method||!method.active||!method.countries.includes(input.address.country)||(method.cities.length&&!method.cities.some(c=>c.toLowerCase()===input.address.city.toLowerCase()))||weight<method.minWeight||(method.maxWeight!==null&&weight>method.maxWeight)||subtotal<method.minOrder||(method.maxOrder!==null&&subtotal>method.maxOrder))throw new BadRequestException('Invalid shipping method for this address or order');if(input.paymentMethod==='COD'&&!method.cod)throw new BadRequestException('Cash on delivery is unavailable for this shipping method');if(input.paymentMethod==='STRIPE'&&!process.env.STRIPE_SECRET_KEY)throw new BadRequestException('Card payments are not configured');
  const shipping=freeShipping||(method.freeAbove!==null&&subtotal-discount>=method.freeAbove)?0:method.price;
  const taxes=await tx.taxRule.findMany({where:{active:true,country:input.address.country}});let tax=0,additional=0;for(const line of lines){const rule=taxes.find(t=>t.taxClass===line.product.taxClass);if(!rule)continue;const lineBase=Math.round(line.price*line.quantity*(subtotal-discount)/(subtotal||1));const calculated=calculateTax(lineBase,rule.rate,rule.included);tax+=calculated.tax;additional+=calculated.additional;}
  const currencySetting=await tx.siteSetting.findUnique({where:{key:'currency'}});const currency=typeof currencySetting?.value==='string'?currencySetting.value:'PKR';
  return{lines,coupon,method,subtotal,discount,shipping,tax,total:subtotal-discount+shipping+additional,currency};
 }
 async quote(input:CheckoutInput,user?:Principal){const q=await this.db.$transaction(tx=>this.calculate(tx,input,user));return this.quoteView(q);}
 private quoteView(q:Awaited<ReturnType<CheckoutService['calculate']>>){return{subtotal:q.subtotal,discount:q.discount,shipping:q.shipping,tax:q.tax,total:q.total,currency:q.currency,items:q.lines.map(l=>({variantId:l.variantId,name:l.product.name,price:l.price,quantity:l.quantity}))};}
 async create(input:CheckoutInput,user?:Principal){if(!input.idempotencyKey)throw new BadRequestException('An idempotency key is required');const key=input.idempotencyKey;const requestHash=hashToken(JSON.stringify({...input,items:mergeQuantities(input.items).sort((a,b)=>a.variantId.localeCompare(b.variantId)),userId:user?.id||null}));const token=createHmac('sha256',process.env.JWT_REFRESH_SECRET!).update(key).digest('hex');
  const replay=async(existing:Awaited<ReturnType<typeof this.createTransaction>>)=>{if(existing.requestHash!==requestHash)throw new ConflictException('This checkout key has already been used for different details');if(existing.status==='CANCELLED')throw new ConflictException('This checkout attempt has ended. Start again with a new idempotency key.');const paymentUrl=existing.paymentMethod==='STRIPE'?await this.payments.startStripe(existing,token):undefined;return{...orderView(existing),accessToken:token,...(paymentUrl?{paymentUrl}:{})};};
  const existing=await this.db.order.findUnique({where:{idempotencyKey:key},include:orderInclude});if(existing)return replay(existing);
  let order:Awaited<ReturnType<typeof this.createTransaction>>|undefined;
  for(let attempt=0;attempt<3;attempt++){try{order=await this.createTransaction(input,requestHash,hashToken(token),user);break;}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2034'&&attempt<2)continue;if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002'){const existing=await this.db.order.findUnique({where:{idempotencyKey:key},include:orderInclude});if(existing)return replay(existing);}throw e;}}
  if(!order)throw new ConflictException('Unable to reserve stock. Please retry.');
  let paymentUrl:string|undefined;
  if(input.paymentMethod==='STRIPE'){try{paymentUrl=await this.payments.startStripe(order,token);}catch{throw new ServiceUnavailableException('Payment session status is not yet known. Retry this checkout with the same idempotency key.');}}
  await this.email.enqueue(order.email,'order_received',{name:input.address.name,number:order.number,url:`${process.env.APP_URL}/order/${order.id}?token=${token}`,message:`Order ${order.number} received. Track: ${process.env.APP_URL}/order/${order.id}?token=${token}`});
  return{...orderView(order),accessToken:token,...(paymentUrl?{paymentUrl}:{})};
 }
 private async createTransaction(input:CheckoutInput,requestHash:string,accessTokenHash:string,user?:Principal){return this.db.$transaction(async tx=>{const q=await this.calculate(tx,input,user);const number=`VA-${Date.now().toString(36).toUpperCase()}-${randomUUID().slice(0,4).toUpperCase()}`;
  const order=await tx.order.create({data:{number,userId:user?.id,email:input.email,accessTokenHash,idempotencyKey:input.idempotencyKey!,requestHash,paymentMethod:input.paymentMethod,subtotal:q.subtotal,discount:q.discount,shipping:q.shipping,tax:q.tax,total:q.total,currency:q.currency,address:input.address as unknown as Prisma.InputJsonValue,shippingMethodId:q.method.id,couponId:q.coupon?.id,expiresAt:input.paymentMethod==='STRIPE'?new Date(Date.now()+35*60000):null,items:{create:q.lines.map(l=>({productId:l.product.id,variantId:l.variant.id,name:l.product.name,sku:l.variant.sku,size:l.variant.size,color:l.variant.color,image:l.variant.image||l.product.images[0]?.url||'',price:l.price,quantity:l.quantity}))},history:{create:{status:'PENDING',note:'Order placed'}},payments:{create:{provider:input.paymentMethod,amount:q.total}}}});
  for(const line of q.lines){let remaining=line.quantity;for(const inventory of line.variant.inventory.sort((a,b)=>a.id.localeCompare(b.id))){const take=Math.min(remaining,inventory.quantity-inventory.reserved);if(take<=0)continue;const changed=await tx.inventory.updateMany({where:{id:inventory.id,quantity:inventory.quantity,reserved:inventory.reserved},data:{quantity:{decrement:take}}});if(!changed.count)throw new ConflictException('Stock changed during checkout. Please try again.');await tx.inventoryTransaction.create({data:{variantId:line.variant.id,warehouseId:inventory.warehouseId,delta:-take,type:'SALE',reason:`Order ${number}`,orderId:order.id}});remaining-=take;if(remaining===0)break;}if(remaining)throw new ConflictException('Insufficient stock');}
  if(q.coupon)await tx.coupon.update({where:{id:q.coupon.id},data:{usedCount:{increment:1}}});
  if(user){const cart=await tx.cart.findUnique({where:{userId:user.id}});if(cart)await tx.cartItem.deleteMany({where:{cartId:cart.id}});}
  await tx.notification.create({data:{title:'New order',body:`${number} · ${input.email}`}});
  return tx.order.findUniqueOrThrow({where:{id:order.id},include:orderInclude});
 },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,timeout:15000});}
}
