import {BadRequestException,Inject,Injectable} from '@nestjs/common';
import {Prisma} from '@prisma/client';
import Stripe from 'stripe';
import {PrismaService} from '../common/prisma.service';
import {audit} from '../common/audit';
import {canTransition} from './rules';
import {orderInclude,orderView} from './order-view';
import {PaymentService} from './payment.service';
import {EmailService} from '../communications/email.service';
export function reservedRefundAmount(refunds:{amount:number;status:string}[]){return refunds.filter(refund=>refund.status!=='FAILED').reduce((sum,refund)=>sum+refund.amount,0);}
export function canMarkReturnRefunded(total:number,refunds:{amount:number;status:string}[]){return refunds.filter(refund=>refund.status==='COMPLETED').reduce((sum,refund)=>sum+refund.amount,0)>=total;}
function isDefinitiveStripeRejection(error:unknown){return error instanceof Stripe.errors.StripeInvalidRequestError||error instanceof Stripe.errors.StripeCardError;}
@Injectable()
export class OrdersService {
 constructor(@Inject(PrismaService) private db:PrismaService,@Inject(PaymentService) private payments:PaymentService,@Inject(EmailService) private email:EmailService){}
 async status(id:string,data:{status:string;note:string;trackingNumber?:string;trackingUrl?:string},actor:string){const order=await this.db.$transaction(async tx=>{const before=await tx.order.findUniqueOrThrow({where:{id},include:orderInclude});if(!canTransition(before.status,data.status))throw new BadRequestException(`Cannot change ${before.status} to ${data.status}`);if(data.status==='CONFIRMED'&&before.paymentMethod==='STRIPE'&&before.paymentStatus!=='PAID')throw new BadRequestException('Awaiting verified online payment');if(data.status==='CANCELLED'){await this.payments.restock(tx,id);if(before.couponId)await tx.coupon.update({where:{id:before.couponId},data:{usedCount:{decrement:1}}});}
  const paid=before.paymentMethod==='COD'&&data.status==='DELIVERED';if(paid){const payment=before.payments[0];await tx.payment.update({where:{id:payment.id},data:{status:'PAID'}});await tx.paymentTransaction.create({data:{paymentId:payment.id,eventId:`cod-${id}`,type:'CAPTURE',amount:before.total}});}
  const result=await tx.order.update({where:{id},data:{status:data.status,trackingNumber:data.trackingNumber,trackingUrl:data.trackingUrl,...(paid?{paymentStatus:'PAID'}:{}),...(data.status==='CANCELLED'&&before.paymentStatus==='PENDING'?{paymentStatus:'CANCELLED',expiresAt:null}:{}),history:{create:{status:data.status,note:data.note}}},include:orderInclude});await audit(tx,actor,'status','orders',id,{status:before.status},{status:data.status,note:data.note});await tx.notification.create({data:{userId:before.userId,title:`Order ${before.number}: ${data.status.replaceAll('_',' ')}`,body:data.note}});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});await this.email.enqueue(order.email,'order_status',{number:order.number,status:data.status,message:`Order ${order.number} is ${data.status}. ${data.note}`});return orderView(order,true);}
 async markPaid(id:string,actor:string,reference:string){return this.db.$transaction(async tx=>{const o=await tx.order.findUniqueOrThrow({where:{id},include:orderInclude});if(o.paymentMethod!=='BANK_TRANSFER'||o.paymentStatus!=='PENDING'||o.status==='CANCELLED')throw new BadRequestException('This payment cannot be manually confirmed');await tx.payment.update({where:{id:o.payments[0].id},data:{status:'PAID'}});await tx.paymentTransaction.create({data:{paymentId:o.payments[0].id,eventId:`bank-${id}`,type:'CAPTURE',amount:o.total}});const result=await tx.order.update({where:{id},data:{paymentStatus:'PAID',status:'CONFIRMED',history:{create:{status:'CONFIRMED',note:`Bank transfer confirmed: ${reference}`}}},include:orderInclude});await audit(tx,actor,'payment_confirmed','orders',id,undefined,{reference});return orderView(result,true);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async refund(id:string,amount:number,reason:string,actor:string){const refund=await this.db.$transaction(async tx=>{const o=await tx.order.findUniqueOrThrow({where:{id},include:{refunds:true,payments:true}});if(!['PAID','PARTIALLY_REFUNDED'].includes(o.paymentStatus))throw new BadRequestException('Only paid orders can be refunded');const refunded=reservedRefundAmount(o.refunds);if(amount<=0||amount+refunded>o.total)throw new BadRequestException('Refund exceeds the remaining paid amount');const refund=await tx.refund.create({data:{orderId:id,amount,reason,status:'PENDING'}});await audit(tx,actor,'refund_requested','orders',id,undefined,{amount,reason});return{refund,order:o};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
  if(refund.order.paymentMethod==='STRIPE'){try{const stripe=new Stripe(process.env.STRIPE_SECRET_KEY!);const payment=refund.order.payments.find(p=>p.provider==='STRIPE');if(!payment?.providerId)throw new Error('Missing original payment');const session=await stripe.checkout.sessions.retrieve(payment.providerId);const intent=typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id;if(!intent)throw new Error('Missing payment intent');const result=await stripe.refunds.create({payment_intent:intent,amount,metadata:{refundId:refund.refund.id,orderId:id}},{idempotencyKey:refund.refund.id});await this.db.refund.update({where:{id:refund.refund.id},data:{providerId:result.id}});if(result.status!=='succeeded')return refund.refund;return this.completeRefund(refund.refund.id,actor,result.id);}catch(error){if(isDefinitiveStripeRejection(error))await this.db.refund.update({where:{id:refund.refund.id},data:{status:'FAILED'}});throw new BadRequestException(isDefinitiveStripeRejection(error)?'Refund provider rejected the request':'Refund outcome is pending provider reconciliation');}}
  return refund.refund;
 }
 async completeRefund(id:string,actor:string,reference:string){return this.db.$transaction(async tx=>{const r=await tx.refund.findUniqueOrThrow({where:{id},include:{order:{include:{payments:true}}}});if(r.status!=='PENDING')throw new BadRequestException('Refund is already resolved');const result=await tx.refund.update({where:{id},data:{status:'COMPLETED',providerId:reference}});const refunds=await tx.refund.aggregate({where:{orderId:r.orderId,status:'COMPLETED'},_sum:{amount:true}});const full=refunds._sum.amount===r.order.total;await tx.order.update({where:{id:r.orderId},data:{paymentStatus:full?'REFUNDED':'PARTIALLY_REFUNDED',history:{create:{status:r.order.status,note:`Refund ${r.amount} minor units completed: ${reference}`}}}});await tx.paymentTransaction.create({data:{paymentId:r.order.payments[0].id,eventId:`refund-${id}`,type:'REFUND',amount:r.amount}});await audit(tx,actor,'refund_completed','refunds',id,undefined,{reference});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async returnStatus(id:string,status:string,note:string,actor:string){const allowed:Record<string,string[]>={REQUESTED:['APPROVED','REJECTED'],APPROVED:['RECEIVED','REJECTED'],RECEIVED:['REFUNDED','CLOSED'],REFUNDED:['CLOSED']};return this.db.$transaction(async tx=>{const r=await tx.returnRequest.findUniqueOrThrow({where:{id},include:{items:{include:{orderItem:true}},order:{include:{refunds:true}}}});if(!allowed[r.status]?.includes(status))throw new BadRequestException('Invalid return status transition');if(status==='RECEIVED'){const warehouse=await tx.warehouse.findFirstOrThrow();for(const item of r.items){await tx.inventory.upsert({where:{variantId_warehouseId:{variantId:item.orderItem.variantId,warehouseId:warehouse.id}},create:{variantId:item.orderItem.variantId,warehouseId:warehouse.id,quantity:item.quantity},update:{quantity:{increment:item.quantity}}});await tx.inventoryTransaction.create({data:{variantId:item.orderItem.variantId,warehouseId:warehouse.id,delta:item.quantity,type:'RETURN',reason:`Return ${id}`,orderId:r.orderId}});}}// Refunds are not linked to individual returns in the current schema, so require the whole order to be refunded before claiming this return is refunded.
  if(status==='REFUNDED'&&!canMarkReturnRefunded(r.order.total,r.order.refunds))throw new BadRequestException('Complete the full order refund before marking the return refunded');const result=await tx.returnRequest.update({where:{id},data:{status,note}});await audit(tx,actor,'status','returns',id,{status:r.status},{status,note});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
}
