import {BadRequestException,Inject,Injectable} from '@nestjs/common';
import {Interval} from '@nestjs/schedule';
import Stripe from 'stripe';
import {PrismaService} from '../common/prisma.service';
import {FullOrder} from './order-view';
import {Prisma} from '@prisma/client';

type LateRefund={refundId:string;orderId:string;amount:number;paymentIntent:string|null};

@Injectable()
export class PaymentService {
 constructor(@Inject(PrismaService) private db:PrismaService){}
 private stripe(){if(!process.env.STRIPE_SECRET_KEY)throw new BadRequestException('Stripe is not configured');return new Stripe(process.env.STRIPE_SECRET_KEY);}
 async startStripe(order:FullOrder,token:string){const existing=await this.db.payment.findFirst({where:{orderId:order.id,provider:'STRIPE'}});if(existing?.providerId){const session=await this.stripe().checkout.sessions.retrieve(existing.providerId);if(session.status==='open'&&session.url)return session.url;if(session.payment_status==='paid')return `${process.env.APP_URL}/order/${order.id}?token=${token}`;if(session.status==='expired')throw new BadRequestException('The payment session has expired');}const session=await this.stripe().checkout.sessions.create({mode:'payment',customer_email:order.email,client_reference_id:order.id,metadata:{orderId:order.id},line_items:[{price_data:{currency:order.currency.toLowerCase(),product_data:{name:`Order ${order.number}`},unit_amount:order.total},quantity:1}],success_url:`${process.env.APP_URL}/order/${order.id}?token=${token}`,cancel_url:`${process.env.APP_URL}/order/${order.id}?token=${token}`,expires_at:Math.floor(order.createdAt.getTime()/1000)+30*60},{idempotencyKey:order.id});await this.db.payment.updateMany({where:{orderId:order.id,provider:'STRIPE'},data:{providerId:session.id}});if(!session.url)throw new BadRequestException('Payment URL unavailable');return session.url;}
 private async completeRefund(refundId:string,providerId:string,eventId:string){return this.db.$transaction(async tx=>{const refund=await tx.refund.findUnique({where:{id:refundId},include:{order:{include:{payments:true}}}});if(!refund||refund.status==='COMPLETED'||refund.status==='FAILED')return;await tx.refund.update({where:{id:refund.id},data:{status:'COMPLETED',providerId}});const totals=await tx.refund.aggregate({where:{orderId:refund.orderId,status:'COMPLETED'},_sum:{amount:true}});const full=(totals._sum.amount||0)>=refund.order.total;await tx.order.update({where:{id:refund.orderId},data:{paymentStatus:full?'REFUNDED':'PARTIALLY_REFUNDED',history:{create:{status:refund.order.status,note:`Refund ${refund.amount} minor units confirmed by payment provider`}}}});const payment=refund.order.payments.find(item=>item.provider==='STRIPE')||refund.order.payments[0];if(payment)await tx.paymentTransaction.upsert({where:{eventId},create:{paymentId:payment.id,eventId,type:'REFUND',amount:refund.amount},update:{}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 private async refundLatePayment(late:LateRefund){if(!late.paymentIntent){await this.db.notification.create({data:{title:'Late payment needs reconciliation',body:`Order ${late.orderId}: payment captured without a payment intent reference`}});return;}try{const result=await this.stripe().refunds.create({payment_intent:late.paymentIntent,amount:late.amount,metadata:{refundId:late.refundId,orderId:late.orderId,reason:'late_cancelled_payment'}},{idempotencyKey:late.refundId});await this.db.refund.update({where:{id:late.refundId},data:{providerId:result.id}});if(result.status==='succeeded')await this.completeRefund(late.refundId,result.id,`late-refund-${late.refundId}`);}catch(error){const definitive=error instanceof Stripe.errors.StripeInvalidRequestError||error instanceof Stripe.errors.StripeCardError;if(definitive)await this.db.refund.update({where:{id:late.refundId},data:{status:'FAILED'}});await this.db.notification.create({data:{title:'Late payment refund needs reconciliation',body:`Order ${late.orderId}: ${definitive?'provider rejected refund':'refund outcome is unknown'}`}});}}
 async webhook(raw:Buffer,signature:string){if(!process.env.STRIPE_WEBHOOK_SECRET)throw new BadRequestException('Webhook is not configured');let event:Stripe.Event;try{event=this.stripe().webhooks.constructEvent(raw,signature,process.env.STRIPE_WEBHOOK_SECRET);}catch{throw new BadRequestException('Invalid payment signature');}
  if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded'){const session=event.data.object as Stripe.Checkout.Session;if(session.payment_status!=='paid')return{received:true};let late:LateRefund|undefined;await this.db.$transaction(async tx=>{if(await tx.paymentTransaction.findUnique({where:{eventId:event.id}}))return;let payment=await tx.payment.findUnique({where:{providerId:session.id},include:{order:true}});if(!payment&&session.metadata?.orderId){payment=await tx.payment.findFirst({where:{orderId:session.metadata.orderId,provider:'STRIPE'},include:{order:true}});if(payment&&!payment.providerId)payment=await tx.payment.update({where:{id:payment.id},data:{providerId:session.id},include:{order:true}});}if(!payment||payment.amount!==session.amount_total||payment.order.currency.toLowerCase()!==session.currency||session.metadata?.orderId!==payment.orderId)throw new BadRequestException('Payment details do not match order');if(payment.status==='PAID')return;await tx.paymentTransaction.create({data:{paymentId:payment.id,eventId:event.id,type:'CAPTURE',amount:payment.amount}});await tx.payment.update({where:{id:payment.id},data:{status:'PAID'}});if(payment.order.status==='CANCELLED'){const refund=await tx.refund.create({data:{orderId:payment.orderId,amount:payment.amount,reason:'Automatic refund for payment received after order cancellation',status:'PENDING'}});await tx.order.update({where:{id:payment.orderId},data:{paymentStatus:'PAID',expiresAt:null,history:{create:{status:'CANCELLED',note:'Late payment captured; automatic refund requested'}}}});late={refundId:refund.id,orderId:payment.orderId,amount:payment.amount,paymentIntent:typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id||null};return;}await tx.order.update({where:{id:payment.orderId},data:{paymentStatus:'PAID',expiresAt:null,status:'CONFIRMED',history:{create:{status:'CONFIRMED',note:'Payment confirmed by signed webhook'}}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});if(late)await this.refundLatePayment(late);}
  if(event.type==='checkout.session.expired'){const session=event.data.object as Stripe.Checkout.Session;const payment=await this.db.payment.findUnique({where:{providerId:session.id}});if(payment)await this.cancelUnpaid(payment.orderId,'Payment session expired');}
  if(event.type==='refund.created'||event.type==='refund.updated'){const refund=event.data.object as Stripe.Refund;const localId=refund.metadata?.refundId;if(localId&&refund.status==='succeeded')await this.completeRefund(localId,refund.id,event.id);else if(localId&&(refund.status==='failed'||refund.status==='canceled'))await this.db.refund.updateMany({where:{id:localId,status:'PENDING'},data:{status:'FAILED',providerId:refund.id}});}
  return{received:true};
 }
 async restock(tx:Prisma.TransactionClient,orderId:string){const sales=await tx.inventoryTransaction.findMany({where:{orderId,type:'SALE'}});for(const sale of sales){await tx.inventory.upsert({where:{variantId_warehouseId:{variantId:sale.variantId,warehouseId:sale.warehouseId}},create:{variantId:sale.variantId,warehouseId:sale.warehouseId,quantity:-sale.delta},update:{quantity:{increment:-sale.delta}}});await tx.inventoryTransaction.create({data:{variantId:sale.variantId,warehouseId:sale.warehouseId,delta:-sale.delta,type:'CANCELLED_ORDER',reason:'Cancelled order restock',orderId}});}}
 async cancelUnpaid(orderId:string,note:string){return this.db.$transaction(async tx=>{const o=await tx.order.findUniqueOrThrow({where:{id:orderId}});if(o.status!=='PENDING'||o.paymentStatus==='PAID')return;await tx.order.update({where:{id:orderId},data:{status:'CANCELLED',paymentStatus:'CANCELLED',expiresAt:null,history:{create:{status:'CANCELLED',note}}}});await tx.payment.updateMany({where:{orderId,status:'PENDING'},data:{status:'CANCELLED'}});await this.restock(tx,orderId);if(o.couponId)await tx.coupon.update({where:{id:o.couponId},data:{usedCount:{decrement:1}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 @Interval(60000) async releaseExpired(){const rows=await this.db.order.findMany({where:{status:'PENDING',paymentMethod:'STRIPE',expiresAt:{lt:new Date()}},take:50});for(const o of rows){try{const payment=await this.db.payment.findFirst({where:{orderId:o.id,provider:'STRIPE'}});if(!payment?.providerId){console.error(JSON.stringify({level:'error',event:'payment_session_unknown',orderId:o.id}));continue;}const session=await this.stripe().checkout.sessions.retrieve(payment.providerId);if(session.payment_status==='paid')continue;if(session.status==='open')await this.stripe().checkout.sessions.expire(session.id);if(session.status==='open'||session.status==='expired')await this.cancelUnpaid(o.id,'Payment reservation expired');}catch{console.error(JSON.stringify({level:'error',event:'payment_expiry_failed',orderId:o.id}));}}}
}
