'use client';
import {useState} from 'react';
import {X} from 'lucide-react';
import {api,Field,Resource,Row} from '../lib/api';
import {ProductFields} from './product-fields';
import {EntityPicker,isEntityList,PermissionPicker} from './entity-picker';
import {CmsFields} from './cms-fields';
import {hasRelation,RelationInput} from './relation-input';
export function Editor({resource:r,row,onClose,onSaved}:{resource:Resource;row:Row|null;onClose:()=>void;onSaved:()=>void}){const [value,setValue]=useState<Record<string,unknown>>(()=>Object.fromEntries(r.fields.map(f=>[f.name,f.type==='json'?JSON.stringify(row?.[f.name]??f.default??null,null,2):row?.[f.name]??f.default??(f.type==='boolean'?false:'')])));const [extra,setExtra]=useState<Record<string,unknown>>(()=>row?{images:row.images,variants:row.variants,collectionIds:row.collectionIds}:{});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const structured=r.key==='homepage'?['config']:r.key==='pages'?['body']:r.key==='menus'?['items']:r.key==='products'?['images','variants','collectionIds']:[];return <div className="overlay" onKeyDown={e=>{if(e.key==='Escape')onClose()}}><form role="dialog" aria-modal="true" aria-label={r.label+' editor'} className="drawer" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const payload:Record<string,unknown>={};for(const f of r.fields){const v=value[f.name];if(f.type==='password'&&!v)continue;payload[f.name]=hasRelation(f.name)&&v===''?null:f.type==='json'&&typeof v==='string'?(v.trim()?JSON.parse(v):null):f.type==='number'?(v===''?null:Number(v)):f.type==='datetime'?(v?new Date(String(v)).toISOString():null):v}if(typeof payload.slug==='string')payload.slug=normalizeSlug(payload.slug);if(r.key==='products'){if(!Array.isArray(extra.variants)||!extra.variants.length)throw new Error('Product variants: add at least one variant with a SKU, color and size before saving.');Object.assign(payload,extra);}await api(`/admin/${r.key}${row?'/'+row.id:''}`,row?'PATCH':'POST',payload);onSaved()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}><header className="drawer-header"><div><span className="eyebrow">{row?'EDIT RECORD':'NEW RECORD'}</span><h2>{r.label}</h2></div><button type="button" className="icon" aria-label="Close editor" onClick={onClose}><X/></button></header><div className="drawer-body"><p className="muted">Monetary fields use paisa (100 paisa = PKR 1). Dates use your local time zone.</p><div className="form-grid">{r.fields.filter(f=>!structured.includes(f.name)).map(f=><FieldInput key={f.name} field={{...f,required:f.required||(r.key==='campaigns'&&['startsAt','endsAt','headline'].includes(f.name))||(r.key==='users'&&!row&&f.name==='password')}} value={value[f.name]} onChange={v=>setValue({...value,[f.name]:v})}/>)}</div>{r.key==='products'&&<ProductFields value={extra} onChange={setExtra}/>}<CmsFields resource={r.key} value={value} onChange={setValue}/>{error&&<div className="error" role="alert">{error}</div>}</div><footer className="drawer-footer"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></footer></form></div>}
function FieldInput({field:f,value,onChange}:{field:Field;value:unknown;onChange:(v:unknown)=>void}){const id='field-'+f.name;const required=f.required;return <div className={['textarea','json'].includes(f.type)?'form-field wide':'form-field'}><label htmlFor={id}>{f.label}{required?' *':''}</label>{f.name==='permissions'?<PermissionPicker value={value} onChange={onChange}/>:isEntityList(f.name)?<EntityPicker name={f.name} value={value} onChange={onChange}/>:hasRelation(f.name)&&!f.options?.length?<RelationInput name={f.name} value={String(value||'')} required={required} onChange={onChange}/>:f.type==='boolean'?<input id={id} type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>:f.type==='select'?<select id={id} required={required} value={String(value??'')} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{f.options?.map(option=>{const v=typeof option==='string'?option:option.value;return <option key={v} value={v}>{typeof option==='string'?option:option.label}</option>})}</select>:f.type==='textarea'||f.type==='json'?<textarea id={id} rows={f.type==='json'?5:3} required={required} value={typeof value==='object'?JSON.stringify(value,null,2):String(value??'')} onChange={e=>onChange(e.target.value)}/>:<input id={id} type={f.type==='datetime'?'datetime-local':f.type==='number'?'number':f.type==='password'?'password':'text'} required={required} onBlur={f.name==='slug'?()=>onChange(normalizeSlug(String(value??''))):undefined} aria-describedby={f.name==='slug'?id+'-hint':undefined} value={f.type==='datetime'&&value?localDate(String(value)):String(value??'')} onChange={e=>onChange(e.target.value)}/>} {f.name==='slug'&&<small id={id+'-hint'}>URL name: spaces become hyphens, for example old-money.</small>}</div>}

function localDate(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}

function normalizeSlug(value:string){return value.trim().toLowerCase().replace(/\s+/g,'-')}
