'use client';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api,PageData} from '../lib/api';
const entities:Record<string,string>={productIds:'products',excludedProductIds:'products',categoryIds:'categories',collectionIds:'collections'};
export const isEntityList=(name:string)=>name in entities;
function parse(value:unknown):string[]{try{const parsed=typeof value==='string'?JSON.parse(value):value;return Array.isArray(parsed)?parsed:[]}catch{return []}}
export function EntityPicker({name,value,onChange}:{name:string;value:unknown;onChange:(v:unknown)=>void}){const [search,setSearch]=useState('');const [page,setPage]=useState(1);const ids=parse(value);const query=useQuery({queryKey:['entity-picker',entities[name],search,page],queryFn:()=>api<PageData>(`/admin/${entities[name]}?pageSize=10&page=${page}&q=${encodeURIComponent(search)}`)});return <div className="entity-picker"><input aria-label={`Search ${entities[name]}`} placeholder={`Search ${entities[name]}…`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><small>{ids.length} selected</small>{query.isPending?<p>Loading…</p>:query.error?<p className="error">{query.error.message}</p>:query.data?.items.map(row=><label className="check-row" key={row.id}><input type="checkbox" checked={ids.includes(row.id)} onChange={e=>onChange(e.target.checked?[...ids,row.id]:ids.filter(id=>id!==row.id))}/>{String(row.name||row.title||row.id)}</label>)}<div className="actions"><button type="button" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button type="button" disabled={page*10>=(query.data?.total||0)} onClick={()=>setPage(page+1)}>Next</button><button type="button" disabled={!ids.length} onClick={()=>onChange([])}>Clear selection</button></div></div>}
const permissions=['products.view','products.create','products.edit','products.delete','inventory.edit','orders.view','orders.edit','customers.view','campaigns.manage','cms.manage','users.manage','settings.manage','reports.view'];
export function PermissionPicker({value,onChange}:{value:unknown;onChange:(v:unknown)=>void}){const selected=parse(value);return <div className="permission-picker">{['*',...permissions].map(permission=><label className="check-row" key={permission}><input type="checkbox" checked={selected.includes(permission)} onChange={e=>onChange(e.target.checked?[...selected,permission]:selected.filter(p=>p!==permission))}/>{permission==='*'?'Full administrator access':permission}</label>)}</div>}
