import {BadRequestException,Body,Controller,Delete,Get,Inject,Param,Patch,Post,Put,Query,Req,UseGuards} from '@nestjs/common';
import {z} from 'zod';
import bcrypt from 'bcryptjs';
import {addressSchema,cartItemsSchema,passwordSchema} from '@vanta/validation';
import {PrismaService} from '../common/prisma.service';
import {AuthGuard,AuthRequest} from '../common/security';
import {ok,paging,paginated,parse} from '../common/http';
import {orderInclude,orderView} from '../commerce/order-view';
import {productInclude,serializeProduct} from '../catalog/catalog.service';
import {mergeQuantities} from '../commerce/rules';
import {Prisma} from '@prisma/client';
@Controller('account') @UseGuards(AuthGuard)
export class AccountController {
 constructor(@Inject(PrismaService) private db:PrismaService){}
 @Get('profile') async profile(@Req() req:AuthRequest){return ok(await this.db.user.findUnique({where:{id:req.user!.id},select:{id:true,name:true,email:true,verified:true,marketingOptIn:true,deletionRequestedAt:true}}));}
 @Patch('profile') async updateProfile(@Req() req:AuthRequest,@Body() body:unknown){const data=parse(z.object({name:z.string().trim().min(2).max(100).optional(),marketingOptIn:z.boolean().optional()}).strict(),body);await this.db.user.update({where:{id:req.user!.id},data});return this.profile(req);}
 @Post('change-password') async password(@Req() req:AuthRequest,@Body() body:unknown){const p=parse(z.object({currentPassword:z.string(),password:passwordSchema}).strict(),body);const user=await this.db.user.findUniqueOrThrow({where:{id:req.user!.id}});if(!await bcrypt.compare(p.currentPassword,user.passwordHash))throw new BadRequestException('Current password is incorrect');await this.db.$transaction([this.db.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(p.password,12)}}),this.db.session.updateMany({where:{userId:user.id,id:{not:req.user!.sessionId}},data:{revokedAt:new Date()}})]);return ok({message:'Password changed'});}
 @Post('deletion-request') async deletion(@Req() req:AuthRequest){await this.db.user.update({where:{id:req.user!.id},data:{deletionRequestedAt:new Date(),marketingOptIn:false}});await this.db.notification.create({data:{title:'Account deletion request',body:req.user!.email}});return ok({message:'Your account deletion request has been recorded for review.'});}
 @Get('orders') async orders(@Req() req:AuthRequest,@Query() q:Record<string,string>){const p=paging(q),where={userId:req.user!.id};const[items,total]=await Promise.all([this.db.order.findMany({where,include:orderInclude,skip:p.skip,take:p.take,orderBy:{createdAt:'desc'}}),this.db.order.count({where})]);return ok(paginated(items.map(order=>orderView(order)),total,p.page,p.pageSize));}
 @Get('addresses') async addresses(@Req() req:AuthRequest){return ok(await this.db.customerAddress.findMany({where:{userId:req.user!.id},take:20}));}
 @Post('addresses') async address(@Req() req:AuthRequest,@Body() body:unknown){const p=parse(addressSchema,body);if(await this.db.customerAddress.count({where:{userId:req.user!.id}})>=20)throw new BadRequestException('Address limit reached');return ok(await this.db.customerAddress.create({data:{...p,userId:req.user!.id}}));}
 @Delete('addresses/:id') async removeAddress(@Req() req:AuthRequest,@Param('id') id:string){await this.db.customerAddress.deleteMany({where:{id,userId:req.user!.id}});return ok({deleted:true});}
 @Get('wishlist') async wishlist(@Req() req:AuthRequest){return ok((await this.db.wishlistItem.findMany({where:{userId:req.user!.id,product:{status:'ACTIVE',visibility:true}},include:{product:{include:productInclude}},take:100})).map(w=>serializeProduct(w.product)));}
 @Post('wishlist') async mergeWishlist(@Req() req:AuthRequest,@Body() body:unknown){const p=parse(z.object({productIds:z.array(z.string()).max(100)}),body);const products=await this.db.product.findMany({where:{id:{in:p.productIds},status:'ACTIVE'},select:{id:true}});await this.db.wishlistItem.createMany({data:products.map(p=>({userId:req.user!.id,productId:p.id})),skipDuplicates:true});return this.wishlist(req);}
 @Delete('wishlist/:id') async removeWish(@Req() req:AuthRequest,@Param('id') id:string){await this.db.wishlistItem.deleteMany({where:{userId:req.user!.id,productId:id}});return ok({deleted:true});}
 @Get('cart') async cart(@Req() req:AuthRequest){const cart=await this.db.cart.findUnique({where:{userId:req.user!.id},include:{items:true}});return ok({items:cart?.items.map(i=>({variantId:i.variantId,quantity:i.quantity}))||[]});}
 @Put('cart') async replaceCart(@Req() req:AuthRequest,@Body() body:unknown){const{items}=parse(z.object({items:cartItemsSchema.or(z.array(z.never()).length(0))}).strict(),body);await this.db.$transaction(async tx=>{const cart=await tx.cart.upsert({where:{userId:req.user!.id},create:{userId:req.user!.id,email:req.user!.email},update:{updatedAt:new Date()}});const merged=mergeQuantities(items);const variants=await tx.productVariant.findMany({where:{id:{in:merged.map(i=>i.variantId)},active:true,product:{status:'ACTIVE'}},include:{inventory:true}});const data=merged.flatMap(item=>{const variant=variants.find(v=>v.id===item.variantId);const available=variant?.inventory.reduce((s,i)=>s+i.quantity-i.reserved,0)||0;const quantity=Math.min(item.quantity,available,50);return quantity>0?[{cartId:cart.id,variantId:item.variantId,quantity}]:[];});await tx.cartItem.deleteMany({where:{cartId:cart.id}});if(data.length)await tx.cartItem.createMany({data});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return this.cart(req);}
 @Post('cart') async mergeCart(@Req() req:AuthRequest,@Body() body:unknown){const{items}=parse(z.object({items:cartItemsSchema.or(z.array(z.never()).length(0))}),body);await this.db.$transaction(async tx=>{const cart=await tx.cart.upsert({where:{userId:req.user!.id},create:{userId:req.user!.id,email:req.user!.email},update:{updatedAt:new Date()},include:{items:true}});const merged=mergeQuantities([...cart.items.map(i=>({variantId:i.variantId,quantity:i.quantity})),...items]);const variants=await tx.productVariant.findMany({where:{id:{in:merged.map(i=>i.variantId)},active:true,product:{status:'ACTIVE'}},include:{inventory:true}});for(const item of merged){const variant=variants.find(v=>v.id===item.variantId);if(!variant)continue;const available=variant.inventory.reduce((s,i)=>s+i.quantity-i.reserved,0);const quantity=Math.min(item.quantity,available,50);if(quantity<=0){await tx.cartItem.deleteMany({where:{cartId:cart.id,variantId:item.variantId}});continue;}await tx.cartItem.upsert({where:{cartId_variantId:{cartId:cart.id,variantId:item.variantId}},create:{cartId:cart.id,variantId:item.variantId,quantity},update:{quantity}});}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return this.cart(req);}
 @Get('returns') async returns(@Req() req:AuthRequest,@Query() q:Record<string,string>){const p=paging(q),where={userId:req.user!.id};const[items,total]=await Promise.all([this.db.returnRequest.findMany({where,include:{items:true,order:{select:{number:true}}},skip:p.skip,take:p.take,orderBy:{createdAt:'desc'}}),this.db.returnRequest.count({where})]);return ok(paginated(items,total,p.page,p.pageSize));}
 @Post('returns') async requestReturn(@Req() req:AuthRequest,@Body() body:unknown){const p=parse(z.object({orderId:z.string(),reason:z.string().min(3).max(300),description:z.string().max(3000).default(''),items:z.array(z.object({orderItemId:z.string(),quantity:z.number().int().min(1).max(50)})).min(1).max(100),images:z.array(z.url()).max(5).default([])}),body);
  const result=await this.db.$transaction(async tx=>{const order=await tx.order.findFirst({where:{id:p.orderId,userId:req.user!.id,status:'DELIVERED'},include:{items:{include:{returnItems:{include:{request:true}}}}}});if(!order)throw new BadRequestException('Only delivered orders can be returned');if(new Set(p.items.map(i=>i.orderItemId)).size!==p.items.length)throw new BadRequestException('Duplicate return items');for(const item of p.items){const original=order.items.find(i=>i.id===item.orderItemId);const already=original?.returnItems.filter(i=>!['REJECTED','CLOSED'].includes(i.request.status)).reduce((s,i)=>s+i.quantity,0)||0;if(!original||item.quantity+already>original.quantity)throw new BadRequestException('Return quantity exceeds purchased quantity');}return tx.returnRequest.create({data:{orderId:p.orderId,userId:req.user!.id,reason:p.reason,description:p.description,images:p.images,items:{create:p.items}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});await this.db.notification.create({data:{title:'Return requested',body:result.id}});return ok(result);
 }
}
