import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const base=process.env.TEST_API_URL||'http://localhost:4000/api';
if(!/^http:\/\/(localhost|127\.0\.0\.1):/.test(base))throw new Error('Integration mutation tests require a local test API');
const suffix=Date.now().toString(36);
async function call(path,{method='GET',body,cookie,origin='http://localhost:3000'}={}){const res=await fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...(origin?{Origin:origin}:{})},body:body?JSON.stringify(body):undefined});const json=await res.json();return{status:res.status,data:json.data,message:json.message,cookie:res.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ')};}
const passed=[];async function test(name,fn){await fn();passed.push(name);console.log('PASS',name);}
let admin,product,order,shipping,category;
const address={name:'QA Customer',phone:'03001234567',line1:'123 Test Avenue',city:'Lahore',postalCode:'54000',country:'PK'};
await test('health and persisted seeded catalog',async()=>{assert.equal((await call('/health')).status,200);const catalog=await call('/products');assert(catalog.data.total>=24);assert(catalog.data.items[0].variants.length>0);assert.equal(catalog.data.items[0].costPrice,undefined);category=(await call('/categories')).data[0];shipping=(await call('/shipping')).data[0];});
await test('admin authentication and unauthenticated denial',async()=>{assert.equal((await call('/admin/orders')).status,401);const login=await call('/auth/login',{method:'POST',body:{email:process.env.SEED_ADMIN_EMAIL||'admin@example.com',password:process.env.SEED_ADMIN_PASSWORD}});assert.equal(login.status,201,login.message);admin=login.cookie;assert(admin.includes('access_token='));assert.equal((await call('/admin/resources',{cookie:admin})).status,200);});
await test('admin-created variant appears on public storefront API',async()=>{const result=await call('/admin/products',{method:'POST',cookie:admin,body:{name:`QA Transaction Tee ${suffix}`,slug:`qa-transaction-${suffix}`,sku:`QA-${suffix}`,categoryId:category.id,price:150000,status:'ACTIVE',images:[{url:'/images/tee-black.png',alt:'Test tee',position:0}],variants:[{sku:`QA-${suffix}-M`,color:'Black',colorHex:'#161616',size:'M',stock:1,active:true}]}});assert.equal(result.status,201,JSON.stringify(result));product=result.data;const pub=await call(`/products/${product.slug}`);assert.equal(pub.data.name,product.name);assert.equal(pub.data.variants[0].stock,1);assert.equal(pub.data.costPrice,undefined);});
const checkout=()=>({email:`qa-${suffix}@example.com`,address,shippingMethodId:shipping.id,paymentMethod:'COD',items:[{variantId:product.variants[0].id,quantity:1}],idempotencyKey:randomUUID()});
await test('every permitted administrator resource can be listed',async()=>{const metadata=await call('/admin/resources',{cookie:admin});for(const resource of metadata.data){const result=await call(`/admin/${resource.key}`,{cookie:admin});assert.equal(result.status,200,`${resource.key}: ${result.message}`);assert(Array.isArray(result.data.items),resource.key);}});
await test('checkout rejects client prices and aggregates duplicate variant quantities',async()=>{const payload=checkout();assert.equal((await call('/checkout/quote',{method:'POST',body:{...payload,total:1}})).status,400);assert.equal((await call('/checkout/quote',{method:'POST',body:{...payload,items:[...payload.items,...payload.items]}})).status,409);});
let request;
await test('concurrent checkout sells one unit exactly once',async()=>{request=checkout();const competing=checkout();const results=await Promise.all([call('/checkout',{method:'POST',body:request}),call('/checkout',{method:'POST',body:competing})]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409],JSON.stringify(results));const index=results.findIndex(r=>r.status===201);order=results[index].data;request=index===0?request:competing;assert.equal(order.total,175000);assert.equal((await call(`/products/${product.slug}`)).data.variants[0].stock,0);assert.equal(order.payments?.[0]?.providerId,undefined);});
await test('idempotency replay does not create or charge twice',async()=>{const replay=await call('/checkout',{method:'POST',body:request});assert.equal(replay.status,201);assert.equal(replay.data.id,order.id);assert.equal((await call(`/products/${product.slug}`)).data.variants[0].stock,0);const changed=await call('/checkout',{method:'POST',body:{...request,email:'different@example.com'}});assert.equal(changed.status,409);});
await test('guest order requires its own access token',async()=>{assert.equal((await call(`/orders/${order.id}`)).status,404);assert.equal((await call(`/orders/${order.id}?token=wrong`)).status,404);const allowed=await call(`/orders/${order.id}?token=${order.accessToken}`);assert.equal(allowed.status,200);assert.equal(allowed.data.requestHash,undefined);assert.equal(allowed.data.accessTokenHash,undefined);});
await test('admin sees the order, cancellation restores stock only once',async()=>{const record=await call(`/admin/orders/${order.id}`,{cookie:admin});assert.equal(record.status,200);assert.equal(record.data.number,order.number);const cancelled=await call(`/admin/orders/${order.id}/status`,{method:'POST',cookie:admin,body:{status:'CANCELLED',note:'QA cancellation'}});assert.equal(cancelled.status,201,cancelled.message);assert.equal((await call(`/products/${product.slug}`)).data.variants[0].stock,1);assert.equal((await call(`/admin/orders/${order.id}/status`,{method:'POST',cookie:admin,body:{status:'CANCELLED',note:'Duplicate'}})).status,400);assert.equal((await call(`/products/${product.slug}`)).data.variants[0].stock,1);});
await test('CSRF blocks cookie mutation from an untrusted origin',async()=>{const result=await call('/admin/inventory/adjust',{method:'POST',cookie:admin,origin:'https://attacker.example',body:{variantId:product.variants[0].id,delta:1,reason:'CSRF test'}});assert.equal(result.status,403);});
await test('delegated user managers cannot grant themselves super-admin',async()=>{const role=await call('/admin/roles',{method:'POST',cookie:admin,body:{name:`QA Limited ${suffix}`,permissions:['users.manage']}});assert.equal(role.status,201,role.message);const user=await call('/admin/users',{method:'POST',cookie:admin,body:{name:'QA Limited',email:`qa-manager-${suffix}@example.com`,password:'QaManagerPassword2026!',roleId:role.data.id,active:true}});assert.equal(user.status,201,user.message);const login=await call('/auth/login',{method:'POST',body:{email:user.data.email,password:'QaManagerPassword2026!'}});const roles=await call('/admin/roles',{cookie:admin});const superRole=roles.data.items.find(r=>r.name==='Super Admin');assert.equal((await call(`/admin/users/${user.data.id}`,{method:'PATCH',cookie:login.cookie,body:{name:'Escalation',email:user.data.email,roleId:superRole.id,active:true}})).status,403);assert.equal((await call('/admin/orders',{cookie:login.cookie})).status,403);});
await test('CMS changes are visible without source edits',async()=>{const settings=await call('/admin/settings',{cookie:admin});const row=settings.data.items.find(s=>s.key==='brandName')||(await call('/admin/settings?pageSize=100',{cookie:admin})).data.items.find(s=>s.key==='brandName');const edited=await call(`/admin/settings/${row.id}`,{method:'PATCH',cookie:admin,body:{key:row.key,value:'QA CMS Brand'}});assert.equal(edited.status,200,edited.message);assert.equal((await call('/content')).data.settings.brandName,'QA CMS Brand');await call(`/admin/settings/${row.id}`,{method:'PATCH',cookie:admin,body:{key:row.key,value:row.value}});});
await test('refresh rotation invalidates the old session and logout invalidates new session',async()=>{const initial=await call('/auth/login',{method:'POST',body:{email:process.env.SEED_ADMIN_EMAIL||'admin@example.com',password:process.env.SEED_ADMIN_PASSWORD}});const next=await call('/auth/refresh',{method:'POST',cookie:initial.cookie});assert.equal(next.status,201);assert.equal((await call('/auth/me',{cookie:initial.cookie})).status,401);assert.equal((await call('/auth/me',{cookie:next.cookie})).status,200);await call('/auth/logout',{method:'POST',cookie:next.cookie});assert.equal((await call('/auth/me',{cookie:next.cookie})).status,401);});
await call('/admin/products/bulk',{method:'POST',cookie:admin,body:{ids:[product.id],action:'archive'}});
await test('highest-rated products use descending average ratings across pages',async()=>{const result=await call('/products?sort=rating&pageSize=100');assert.equal(result.status,200,result.message);const ratings=result.data.items.map(p=>p.rating);assert.deepEqual(ratings,[...ratings].sort((a,b)=>b-a));const page=await call('/products?sort=rating&pageSize=3&page=2');assert.deepEqual(page.data.items.map(p=>p.id),result.data.items.slice(3,6).map(p=>p.id));});
await test('customer wishlist, exact cart replacement and addresses persist',async()=>{
 const created=await call('/auth/register',{method:'POST',body:{name:'QA Customer',email:`qa-customer-${suffix}@example.com`,password:'QaCustomerPassword2026!'}});assert.equal(created.status,201,created.message);const cookie=created.cookie;
 const catalog=(await call('/products')).data.items;const chosen=catalog.find(p=>p.variants.some(v=>v.active&&v.stock>0));const variant=chosen.variants.find(v=>v.active&&v.stock>0);
 assert.equal((await call('/account/wishlist',{method:'POST',cookie,body:{productIds:[chosen.id]}})).status,201);assert((await call('/account/wishlist',{cookie})).data.some(p=>p.id===chosen.id));
 const body={items:[{variantId:variant.id,quantity:1}]};await call('/account/cart',{method:'PUT',cookie,body});await call('/account/cart',{method:'PUT',cookie,body});assert.deepEqual((await call('/account/cart',{cookie})).data.items,body.items);
 const saved=await call('/account/addresses',{method:'POST',cookie,body:address});assert.equal(saved.status,201,saved.message);assert((await call('/account/addresses',{cookie})).data.some(a=>a.id===saved.data.id));
 await call(`/account/addresses/${saved.data.id}`,{method:'DELETE',cookie});await call(`/account/wishlist/${chosen.id}`,{method:'DELETE',cookie});await call('/account/cart',{method:'PUT',cookie,body:{items:[]}});assert.deepEqual((await call('/account/cart',{cookie})).data.items,[]);
});
await test('administrator coupon configuration changes checkout totals',async()=>{
 const chosen=(await call('/products')).data.items.find(p=>p.variants.some(v=>v.active&&v.stock>0));const variant=chosen.variants.find(v=>v.active&&v.stock>0);const input={...checkout(),items:[{variantId:variant.id,quantity:1}]};const baseline=await call('/checkout/quote',{method:'POST',body:input});assert.equal(baseline.status,201,baseline.message);
 const body={name:`QA Coupon ${suffix}`,code:`QA${suffix}`,type:'PERCENTAGE',value:10,productIds:[chosen.id],active:true};const coupon=await call('/admin/coupons',{method:'POST',cookie:admin,body});assert.equal(coupon.status,201,coupon.message);
 const discounted=await call('/checkout/quote',{method:'POST',body:{...input,couponCode:body.code}});assert.equal(discounted.status,201,discounted.message);assert.equal(discounted.data.discount,Math.round(baseline.data.subtotal*0.1));
 await call(`/admin/coupons/${coupon.data.id}`,{method:'PATCH',cookie:admin,body:{...body,active:false}});assert.equal((await call('/checkout/quote',{method:'POST',body:{...input,couponCode:body.code}})).status,400);
});
await test('scheduled campaigns respect future, current and expired windows',async()=>{
 const now=Date.now();const body={name:`QA Campaign ${suffix}`,slug:`qa-campaign-${suffix}`,headline:'QA scheduled campaign',themeColor:'#ffffff',textColor:'#000000',status:'SCHEDULED',startsAt:new Date(now+3600000).toISOString(),endsAt:new Date(now+7200000).toISOString()};
 const campaign=await call('/admin/campaigns',{method:'POST',cookie:admin,body});assert.equal(campaign.status,201,campaign.message);assert.equal((await call(`/campaigns/${body.slug}`)).status,404);
 await call(`/admin/campaigns/${campaign.data.id}`,{method:'PATCH',cookie:admin,body:{...body,startsAt:new Date(now-3600000).toISOString()}});assert.equal((await call(`/campaigns/${body.slug}`)).status,200);
 await call(`/admin/campaigns/${campaign.data.id}`,{method:'PATCH',cookie:admin,body:{...body,startsAt:new Date(now-7200000).toISOString(),endsAt:new Date(now-3600000).toISOString()}});assert.equal((await call(`/campaigns/${body.slug}`)).status,404);
 const audits=await call('/admin/audit-logs?q=campaigns',{cookie:admin});assert.equal(audits.status,200);assert(audits.data.items.some(a=>a.entityId===campaign.data.id));
});
await test('minimum rating filter excludes lower-rated products',async()=>{const result=await call('/products?rating=4&sort=rating&pageSize=100');assert.equal(result.status,200,result.message);assert(result.data.items.length>0);assert(result.data.items.every(p=>p.rating>=4));});
console.log(`\n${passed.length} integration scenarios passed. QA fixtures are identified by ${suffix}.`);



