'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import type { User, Order, Paginated } from '@vanta/types';
import { api,post,money,errorMessage } from '@/lib/api';
import { AccountAuth } from './account-auth';
import { useShop } from '@/lib/store';
import { AccountAddresses,AccountProfile,AccountReturns } from './account-panels';
export function Account(){const client=useQueryClient();const {data:user,isLoading}=useQuery({queryKey:['me'],queryFn:()=>api<User>('/auth/me'),retry:false});const [tab,setTab]=useState('Orders'),[message,setMessage]=useState('');if(isLoading)return <div className="loading-page"><p>Opening your account…</p></div>;if(!user)return <AccountAuth onLogin={user=>{client.setQueryData(['me'],user);client.invalidateQueries({queryKey:['account-orders']});}}/>;return <section className="section"><div className="section-heading"><div><span className="eyebrow">YOUR STUDIO</span><h2>Good to see you, {user.name.split(' ')[0]}.</h2></div></div>{!user.verified&&<div className="account-card between"><p style={{margin:0}}>Verify your email to keep your account up to date.</p><button className="underlined" onClick={async()=>{try{await post('/auth/resend-verification');setMessage('Verification email sent.');}catch(error){setMessage(errorMessage(error));}}}>Resend verification</button></div>}{message&&<p role="status" className="form-message">{message}</p>}<div className="account-layout"><nav className="account-nav" aria-label="Account navigation">{['Orders','Addresses','Profile','Returns'].map(name=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}<Link href="/wishlist">Wishlist</Link><button onClick={async()=>{try{await post('/auth/logout');useShop.setState({items:[],wishlist:[],cartOwner:null,authenticatedUser:null});client.clear();}catch(error){setMessage(errorMessage(error));}}}>Sign out</button></nav><div>{tab==='Orders'?<AccountOrders/>:tab==='Addresses'?<AccountAddresses/>:tab==='Profile'?<AccountProfile user={user}/>:<AccountReturns/>}</div></div></section>;}
function AccountOrders(){const [page,setPage]=useState(1);const {data,error,isLoading}=useQuery({queryKey:['account-orders',page],queryFn:()=>api<Paginated<Order>>(`/account/orders?page=${page}&pageSize=10`)});return <><h2>Your orders</h2>{isLoading&&<p>Loading orders…</p>}{error&&<p className="error-message">{error.message}</p>}{data?.items.length?data.items.map(order=><article className="account-card" key={order.id}><div className="between"><div><h3>{order.number}</h3><p className="muted">{new Date(order.createdAt).toLocaleDateString()} · {order.items.length} pieces</p></div><span className="status-pill">{order.status.replaceAll('_',' ')}</span></div><div className="between"><strong>{money(order.total,order.currency)}</strong><Link className="button outline" href={`/orders/${order.id}`}>View order ↗</Link></div></article>):!isLoading&&!error&&<div className="empty-state"><h3>Your first chapter is waiting.</h3><p>Your orders will appear here.</p><Link href="/shop" className="button">Explore the collection</Link></div>}{data&&data.pages>1&&<nav className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>{page} / {data.pages}</span><button disabled={page>=data.pages} onClick={()=>setPage(page+1)}>Next</button></nav>}</>;}


