'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {User} from '@vanta/types';
import {post,errorMessage} from '@/lib/api';
import {ArrowUpRight} from './icons';
export function AccountAuth({onLogin}:{onLogin:(user:User)=>void}){
 const [mode,setMode]=useState<'login'|'register'|'forgot'>('login'),[message,setMessage]=useState(''),[pending,setPending]=useState(false);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setMessage('');const values=Object.fromEntries(new FormData(event.currentTarget));try{if(mode==='forgot'){await post('/auth/forgot-password',{email:values.email});setMessage('If an account exists for this email, a reset link is on its way.');}else onLogin(await post<User>(`/auth/${mode}`,values));}catch(error){setMessage(errorMessage(error));}finally{setPending(false);}}
 const adminUrl=process.env.NEXT_PUBLIC_ADMIN_URL||'http://localhost:3001/admin';
 return <div className="auth-wrap"><span className="eyebrow">YOUR CORNER OF THE STUDIO</span><h1>{mode==='login'?'Welcome back.':mode==='register'?'Make yourself at home.':'Let’s get you back in.'}</h1><p>{mode==='login'?'Your orders, favorites and everyday essentials.':mode==='register'?'Join the studio for a more personal everyday.':'We’ll email you a link to reset your password.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Full name<input required minLength={2} name="name" autoComplete="name"/></label>}<label>Email<input type="email" name="email" required autoComplete="email"/></label>{mode!=='forgot'&&<label>Password<input type="password" name="password" minLength={mode==='register'?12:1} required autoComplete={mode==='register'?'new-password':'current-password'}/>{mode==='register'&&<span className="muted" style={{fontSize:10}}>At least 12 characters, with uppercase, lowercase and a number.</span>}</label>}<button disabled={pending} className="button full" type="submit">{pending?'One moment…':mode==='login'?'Sign in':mode==='register'?'Create account':'Send reset link'}<ArrowUpRight size={17}/></button>{message&&<p role="status" className="form-message">{message}</p>}</form><div className="auth-links"><button onClick={()=>{setMode(mode==='login'?'register':'login');setMessage('');}}>{mode==='login'?'New here? Create an account':'Back to sign in'}</button>{mode==='login'&&<button onClick={()=>{setMode('forgot');setMessage('');}}>Forgot password?</button>}</div>{mode==='login'&&<p className="admin-signin-link">Store team? <Link href={adminUrl}>Sign in as admin <ArrowUpRight size={14}/></Link></p>}</div>;
}
