import Link from 'next/link';
import type { SiteContent, Section, Product, Paginated } from '@vanta/types';
import { api, safeHref } from '@/lib/api';
import { ArrowUpRight, ArrowRight } from './icons';
import { ProductCard } from './product-card';
import { Newsletter } from './newsletter';
import { ShopTheLook } from './shop-the-look';
const str=(value:unknown)=>typeof value==='string'?value:'';
function SectionTitle({section}:{section:Section}){return <div className="section-heading"><div><span className="eyebrow">{str(section.config.eyebrow)}</span><h2>{section.title}</h2>{section.subtitle && <p>{section.subtitle}</p>}</div><Link className="text-link" href={safeHref(section.config.ctaUrl)}>{str(section.config.ctaText)||'Explore all'}<ArrowUpRight size={17}/></Link></div>;}
async function SectionView({section,content,index}:{section:Section;content:SiteContent;index:number}){
 const c=section.config;
 if(section.type==='hero') return <section className="hero" style={{color:str(c.textColor)||'#fff'}}><picture>{str(c.mobileImage)&&<source media="(max-width: 650px)" srcSet={str(c.mobileImage)}/>}<img className="hero-image" src={str(c.image)} alt={section.title} fetchPriority="high"/></picture><div className="hero-shade"/><div className="hero-topline"><span>{str(c.eyebrow)}</span><span>EST. MMXXIV · MADE FOR THE EVERYDAY</span></div><div className="hero-content"><div className="hero-copy"><span className="eyebrow">{section.subtitle}</span><h1>{section.title}</h1><div className="hero-actions"><Link href={safeHref(c.ctaUrl)} className="button light">{str(c.ctaText)||'Shop the collection'}<ArrowUpRight size={18}/></Link>{str(c.secondaryText)&&<Link className="text-link" href={safeHref(c.secondaryUrl)}>{str(c.secondaryText)}<ArrowUpRight size={16}/></Link>}</div></div><div className="hero-caption"><span>01 / {String(content.sections.filter(s=>s.enabled).length).padStart(2,'0')}</span><div/><span>LESS, BUT BETTER.</span></div></div><div className="hero-bottom"><span>A NEW POINT OF VIEW.</span><a href="#collection">SCROLL TO EXPLORE ↓</a><span>{content.settings.brandName}®</span></div></section>;
 if(section.type==='products'||section.type==='shop-the-look'){
  const params=new URLSearchParams({pageSize:String(Number(c.columns)||4)});if(Array.isArray(c.productIds)&&c.productIds.length){params.set('ids',c.productIds.join(','));}else{if(c.collectionSlug)params.set('collection',str(c.collectionSlug));if(c.categorySlug)params.set('category',str(c.categorySlug));if(c.gender)params.set('gender',str(c.gender));}
  const result=await api<Paginated<Product>>(`/products?${params}`);const products=Array.isArray(c.productIds)&&c.productIds.length?result.items.filter(p=>(c.productIds as string[]).includes(p.id)):result.items;
  return <section className="section products-section" id={index===1?'collection':section.id}><SectionTitle section={section}/>{section.type==='shop-the-look'&&<ShopTheLook image={str(c.image)} alt={section.title} products={products} markers={Array.isArray(c.markers)?c.markers.filter((m):m is {productId:string;x:number;y:number}=>!!m&&typeof m.productId==='string'&&typeof m.x==='number'&&typeof m.y==='number'):[]} currency={content.settings.currency}/>}<div className="product-grid">{products.map(product=><ProductCard key={product.id} product={product} currency={content.settings.currency}/>)}</div>{!products.length&&<p className="empty-note">The next edit is on its way. Check back soon.</p>}</section>;
 }
 if(section.type==='categories')return <section className="section category-section"><SectionTitle section={section}/><div className="category-grid">{content.categories.filter(category=>!category.parentId).slice(0,4).map((category,i)=><Link className="category-tile" key={category.id} href={`/categories/${category.slug}`}><img src={category.image||''} alt={category.name} loading="lazy"/><span className="category-number">0{i+1}</span><div><h3>{category.name}</h3><ArrowUpRight size={24}/></div></Link>)}</div></section>;
 if(['editorial','campaign','video'].includes(section.type))return <section className={`editorial ${c.imagePosition==='right'?'image-right':''}`} style={{background:str(c.background)||'#e8e6df',color:str(c.textColor)||'#141414'}}><div className="editorial-image">{section.type==='video'?<video controls playsInline poster={str(c.image)} src={str(c.videoUrl)} aria-label={section.title}/>:<img src={str(c.image)} alt={section.title} loading="lazy"/>}<span className="image-note">{content.settings.brandName} / NOTES FROM THE EVERYDAY</span></div><div className="editorial-copy"><span className="eyebrow">{str(c.eyebrow)}</span><h2>{section.title}</h2><p>{section.subtitle}</p><Link className="button" href={safeHref(c.ctaUrl)}>{str(c.ctaText)||'Discover the story'}<ArrowUpRight size={17}/></Link><span className="editorial-index">CONSIDERED IN EVERY DETAIL. <span>0{index+1}</span></span></div></section>;
 if(section.type==='newsletter')return <section className="newsletter-section" style={{background:str(c.background)||undefined,color:str(c.textColor)||undefined}}><span className="eyebrow">{str(c.eyebrow)||'THE INNER CIRCLE'}</span><h2>{section.title}</h2><p>{section.subtitle}</p><Newsletter/></section>;
 if(section.type==='announcement')return <div className="statement" style={{background:str(c.background)||undefined,color:str(c.textColor)||undefined}}><span>{section.title}</span><ArrowRight size={28}/><span>{section.subtitle}</span></div>;
 return <section className="section text-section" style={{background:str(c.background)||undefined,color:str(c.textColor)||undefined}}><span className="eyebrow">{str(c.eyebrow)}</span><h2>{section.title}</h2><p>{section.subtitle}</p>{str(c.ctaText)&&<Link className="text-link" href={safeHref(c.ctaUrl)}>{str(c.ctaText)}<ArrowUpRight size={16}/></Link>}</section>;
}
export async function HomeSections({content}:{content:SiteContent}){const now=Date.now();const sections=content.sections.filter(s=>s.enabled&&(!s.startsAt||new Date(s.startsAt).getTime()<=now)&&(!s.endsAt||new Date(s.endsAt).getTime()>now)).sort((a,b)=>a.position-b.position);return <>{sections.map((section,index)=><SectionView key={section.id} section={section} index={index} content={content}/>)}</>;}


