'use client';
import { useRef,useState } from 'react';
import Link from 'next/link';
import type { Product,Variant } from '@vanta/types';
import { useShop } from '@/lib/store';
import { selectVariant } from '@/lib/cart-core.mjs';
import { money } from '@/lib/api';
import { ArrowUpRight,X } from './icons';
export function QuickAdd({product,currency}:{product:Product;currency:string}){const dialog=useRef<HTMLDialogElement>(null);const colors=[...new Set(product.variants.filter(v=>v.active).map(v=>v.color))];const [color,setColor]=useState(colors[0]||''),[size,setSize]=useState(''),[error,setError]=useState('');const variant=selectVariant(product.variants,color,size) as Variant|undefined;const add=useShop(s=>s.add);return <><button className="quick-view" onClick={()=>dialog.current?.showModal()}>Quick add<ArrowUpRight size={15}/></button><dialog className="quick-dialog" ref={dialog}><div className="between"><span className="eyebrow">A NEW EVERYDAY ESSENTIAL</span><button className="icon-button" aria-label="Close quick add" onClick={()=>dialog.current?.close()}><X size={20}/></button></div><div className="quick-product"><img src={variant?.image||product.images[0]?.url} alt={product.name}/><div><h2>{product.name}</h2><p>{money(variant?.salePrice??variant?.price??product.salePrice??product.price,currency)}</p><label>Color<select value={color} onChange={e=>{setColor(e.target.value);setSize('');}}>{colors.map(c=><option key={c}>{c}</option>)}</select></label><label>Size<select value={size} onChange={e=>{setSize(e.target.value);setError('');}}><option value="">Select a size</option>{product.variants.filter(v=>v.active&&v.color===color).map(v=><option key={v.id} value={v.size} disabled={!v.stock}>{v.size}{!v.stock?' — Sold out':''}</option>)}</select></label><button className="button full" onClick={()=>{if(!variant?.stock){setError('Choose an available size.');return;}add({variantId:variant.id,productId:product.id,name:product.name,slug:product.slug,image:variant.image||product.images[0]?.url||'',size:variant.size,color:variant.color,price:variant.salePrice??variant.price??product.salePrice??product.price,quantity:1,stock:variant.stock});dialog.current?.close();}}>Add to bag<ArrowUpRight size={15}/></button><p role="alert" className="field-error">{error}</p><Link href={`/products/${product.slug}`} className="underlined">View all details</Link></div></div></dialog></>;}
