'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import type { Product,Paginated,SiteContent } from '@vanta/types';
import { api,money } from '@/lib/api';
import { Search,X,ArrowUpRight } from './icons';
export function SearchPanel({onClose,content}:{onClose:()=>void;content:SiteContent|null}){const [query,setQuery]=useState(''),[debounced,setDebounced]=useState(''),[recent,setRecent]=useState<string[]>([]);useEffect(()=>{const timeout=setTimeout(()=>setDebounced(query.trim()),250);return()=>clearTimeout(timeout);},[query]);useEffect(()=>{try{setRecent(JSON.parse(localStorage.getItem('vanta-searches')||'[]'));}catch{/* Optional presentation data unavailable. */}},[]);const {data,isFetching,error}=useQuery({queryKey:['search',debounced],queryFn:()=>api<Paginated<Product>>(`/products?q=${encodeURIComponent(debounced)}&pageSize=4`),enabled:debounced.length>1});const categories=content?.categories.filter(c=>c.name.toLowerCase().includes(debounced.toLowerCase())).slice(0,4)||[];function save(){if(query.trim()){const searches=[query.trim(),...recent.filter(s=>s!==query.trim())].slice(0,5);localStorage.setItem('vanta-searches',JSON.stringify(searches));}onClose();}return <div className="predictive-search"><form className="search-panel" action="/search" onSubmit={save}><Search size={21}/><input autoFocus aria-label="Search products" name="q" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find your next everyday essential"/><button type="submit" className="text-link">Search<ArrowUpRight size={17}/></button><button type="button" className="icon-button" aria-label="Close search" onClick={onClose}><X/></button></form><div className="search-results">{debounced.length>1?<><div className="between"><span className="eyebrow">{isFetching?'SEARCHING THE STUDIO…':`${data?.total||0} PIECES FOUND`}</span><Link href={`/search?q=${encodeURIComponent(query)}`} className="text-link" onClick={save}>See all<ArrowUpRight size={15}/></Link></div>{error&&<p className="error-message">{error.message}</p>}<div className="search-product-grid">{data?.items.map(product=><Link href={`/products/${product.slug}`} className="search-product" key={product.id} onClick={save}><img src={product.images[0]?.url} alt={product.name}/><div><strong>{product.name}</strong><p>{money(product.salePrice??product.price,content?.settings.currency)}</p></div></Link>)}</div>{categories.length>0&&<div className="search-suggestions"><span className="eyebrow">CATEGORIES</span>{categories.map(c=><Link key={c.id} href={`/categories/${c.slug}`} onClick={onClose}>{c.name} ↗</Link>)}</div>}</>:<><span className="eyebrow">{recent.length?'RECENT SEARCHES':'EXPLORE THE STUDIO'}</span><div className="search-suggestions">{recent.map(term=><button key={term} onClick={()=>setQuery(term)}>{term} ↗</button>)}{!recent.length&&content?.collections.slice(0,4).map(c=><Link key={c.id} href={`/collections/${c.slug}`} onClick={onClose}>{c.name} ↗</Link>)}</div></>}</div></div>;}

