'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import type { SiteContent } from '@vanta/types';
import { Search, ShoppingBag, Heart, UserRound, Menu, X, ArrowUpRight, Plus, Minus } from './icons';
import { useShop } from '@/lib/store';
import { money, safeHref } from '@/lib/api';
import { Newsletter } from './newsletter';
import { SearchPanel } from './search-panel';

export function Header({content}: {content: SiteContent | null}) {
 const [menu, setMenu] = useState(false); const [search, setSearch] = useState(false);
 const {items, openBag, hydrated} = useShop();
 return <><a className="skip-link" href="#main">Skip to content</a>{content?.settings.announcementEnabled && <div className="announcement"><Link href={safeHref(content.settings.announcementLink)}>{content.settings.announcement}<ArrowUpRight size={12}/></Link></div>}
 <header className="header"><button className="icon-button mobile-only" aria-label="Open navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button><Link className="wordmark" href="/">{content?.settings.brandName || 'VANTA STUDIO'}<span>®</span></Link><nav className="desktop-nav" aria-label="Main navigation">{content?.menus.header.map(item=><div className="nav-group" key={item.label}><Link href={safeHref(item.href)}>{item.label}</Link>{!!item.children?.length && <div className="mega-menu">{item.children.map(child=><Link key={child.label} href={safeHref(child.href)}>{child.label}<ArrowUpRight size={14}/></Link>)}</div>}</div>)}</nav><div className="header-actions"><button className="icon-button" aria-label="Search products" onClick={()=>setSearch(!search)}><Search size={19}/></button><Link className="icon-button hide-small" href="/account" aria-label="My account"><UserRound size={19}/></Link><Link className="icon-button hide-small" href="/wishlist" aria-label="Wishlist"><Heart size={19}/></Link><button className="bag-button" aria-label={`Open bag, ${hydrated ? items.reduce((n,i)=>n+i.quantity,0) : 0} items`} onClick={()=>openBag(true)}><ShoppingBag size={19}/><span className="bag-label">Bag</span><span className="bag-count">{hydrated ? items.reduce((n,i)=>n+i.quantity,0) : 0}</span></button></div></header>
 {search && <SearchPanel content={content} onClose={()=>setSearch(false)}/>}
 {menu && <nav className="mobile-nav" aria-label="Mobile navigation">{content?.menus.header.map(item=><Link onClick={()=>setMenu(false)} key={item.label} href={safeHref(item.href)}>{item.label}<ArrowUpRight size={22}/></Link>)}<Link href="/account" onClick={()=>setMenu(false)}>My account</Link><Link href="/wishlist" onClick={()=>setMenu(false)}>Wishlist</Link></nav>}
 <BagDrawer currency={content?.settings.currency}/></>;
}
export function BagLines({currency = 'PKR'}: {currency?: string}) { const {items,quantity,remove}=useShop(); return <div className="bag-lines">{items.map(item=><article className="bag-line" key={item.variantId}><Link href={`/products/${item.slug}`}><img src={item.image} alt={item.name}/></Link><div><Link href={`/products/${item.slug}`} className="item-title">{item.name}</Link><p className="muted">{item.color} / {item.size}</p><div className="quantity"><button aria-label={`Decrease ${item.name}`} onClick={()=>quantity(item.variantId,item.quantity-1)}><Minus size={12}/></button><span>{item.quantity}</span><button aria-label={`Increase ${item.name}`} disabled={item.quantity>=Math.min(50,item.stock)} onClick={()=>quantity(item.variantId,item.quantity+1)}><Plus size={12}/></button></div></div><div className="bag-price"><span>{money(item.price*item.quantity,currency)}</span><button className="underlined muted" onClick={()=>remove(item.variantId)}>Remove</button></div></article>)}</div>; }
function BagDrawer({currency = 'PKR'}: {currency?: string}) {
 const {items,bagOpen,openBag,hydrated}=useShop(); const dialog = useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(bagOpen) dialog.current?.showModal(); else dialog.current?.close();},[bagOpen]);
 return <dialog ref={dialog} className="bag-dialog" onCancel={()=>openBag(false)} onClick={e=>{if(e.target===e.currentTarget)openBag(false);}}><div className="drawer-inner"><div className="drawer-heading"><h2>Your bag <span>({hydrated?items.reduce((n,i)=>n+i.quantity,0):0})</span></h2><button className="icon-button" aria-label="Close bag" onClick={()=>openBag(false)}><X/></button></div>{items.length ? <><p className="drawer-note">Good choices. Made to stay with you.</p><BagLines currency={currency}/><div className="bag-bottom"><div className="between"><span>Subtotal</span><strong>{money(items.reduce((s,i)=>s+i.price*i.quantity,0),currency)}</strong></div><p className="muted">Shipping, discounts and taxes calculated at checkout.</p><Link className="button full" href="/checkout" onClick={()=>openBag(false)}>Checkout<ArrowUpRight size={18}/></Link><Link className="button outline full" href="/cart" onClick={()=>openBag(false)}>View bag</Link></div></> : <div className="empty-state"><ShoppingBag size={36}/><h3>A little room for something good.</h3><p>Your bag is currently empty.</p><Link className="button" href="/shop" onClick={()=>openBag(false)}>Explore the collection<ArrowUpRight size={17}/></Link></div>}</div></dialog>;
}
export function Footer({content}: {content: SiteContent | null}) { return <footer className="footer"><div className="footer-top"><div><span className="eyebrow">THE EVERYDAY, RECONSIDERED.</span><h2>Good things.<br/>On repeat.</h2><p>Considered essentials. A different perspective.</p></div><div className="footer-links">{content?.menus.footer.map(item=><Link key={item.label} href={safeHref(item.href)}>{item.label}<ArrowUpRight size={12}/></Link>)}</div><div className="footer-signup"><span className="eyebrow">IN THE KNOW</span><p>New collections, studio notes, and a little more.</p><Newsletter compact/></div></div><div className="footer-wordmark">{content?.settings.brandName || 'VANTA STUDIO'}<sup>®</sup></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {content?.settings.brandName || 'VANTA STUDIO'}</span><span>Designed for a life in motion.</span><span>{content?.settings.currency || 'PKR'} · Pakistan</span></div></footer>; }


