import { resource } from '@/lib/server-api';
import type { Metadata } from 'next';
import type { Product,Paginated,SiteContent } from '@vanta/types';
import { api } from '@/lib/api';
import { ProductDetail } from '@/components/product-detail';
import { ProductCard } from '@/components/product-card';
import { Reviews } from '@/components/reviews';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;try{const product=await resource<Product>(`/products/${slug}`);return {title:product.seoTitle||product.name,description:product.seoDescription||product.shortDescription,alternates:{canonical:`/products/${slug}`},openGraph:{images:product.images.map(i=>i.url)}};}catch{return {title:'Product unavailable'};}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [product,content]=await Promise.all([resource<Product>(`/products/${slug}`),api<SiteContent>('/content')]);const related=await api<Paginated<Product>>(`/products?category=${product.category.slug}&pageSize=5`);const jsonLd={'@context':'https://schema.org','@type':'Product',name:product.name,description:product.description,image:product.images.map(i=>i.url),sku:product.sku,brand:{'@type':'Brand',name:content.settings.brandName},offers:{'@type':'Offer',priceCurrency:content.settings.currency,price:(product.salePrice??product.price)/100,availability:product.variants.some(v=>v.active&&v.stock>0)?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:`${process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000'}/products/${slug}`}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,'\\u003c')}}/><ProductDetail product={product} currency={content.settings.currency}/><Reviews productId={product.id}/>{related.items.some(p=>p.id!==product.id)&&<section className="section"><div className="section-heading"><div><span className="eyebrow">IN GOOD COMPANY</span><h2>Complete your rotation.</h2></div></div><div className="product-grid">{related.items.filter(p=>p.id!==product.id).slice(0,4).map(p=><ProductCard product={p} currency={content.settings.currency} key={p.id}/>)}</div></section>}</>;}

