export interface MediaImage { id?: string; url: string; alt: string; position?: number }
export interface Variant { id: string; sku: string; color: string; colorHex: string; size: string; price: number | null; salePrice?: number | null; stock: number; image?: string | null; active: boolean }
export interface Category { id: string; name: string; slug: string; description?: string; image?: string | null; parentId?: string | null }
export interface Collection { id: string; name: string; slug: string; description?: string; image?: string | null; rules?: Record<string, unknown> | null }
export interface Product { id: string; name: string; slug: string; sku: string; description: string; shortDescription: string; price: number; salePrice: number | null; gender: string; status: string; featured: boolean; isNew: boolean; bestSeller: boolean; material: string; fit: string; care: string; video?: string; modelInfo?: string; shippingInfo?: string; returnInfo?: string; tags: string[]; categoryId: string; category: Category; images: MediaImage[]; variants: Variant[]; collections: Collection[]; rating: number; reviewCount: number; seoTitle?: string | null; seoDescription?: string | null; sizeGuide?: Record<string, unknown> | null }
export interface Section { id: string; type: string; title: string; subtitle: string; position: number; enabled: boolean; config: Record<string, unknown>; campaignId?: string | null; startsAt?: string | null; endsAt?: string | null }
export interface MenuItem { id?: string; label: string; href: string; children?: MenuItem[]; image?: string }
export interface SiteSettings { brandName: string; tagline: string; currency: string; contactEmail: string; announcement: string; announcementLink: string; announcementEnabled: boolean; logo?: string; instagram?: string; freeShippingThreshold: number; [key: string]: unknown }
export interface SiteContent { settings: SiteSettings; sections: Section[]; menus: { header: MenuItem[]; footer: MenuItem[] }; categories: Category[]; collections: Collection[] }
export interface Paginated<T> { items: T[]; total: number; page: number; pageSize: number; pages: number }
export interface CartLine { variantId: string; quantity: number; productId: string; name: string; slug: string; image: string; size: string; color: string; price: number; stock: number }
export interface Address { name: string; phone: string; line1: string; line2?: string; city: string; region?: string; postalCode: string; country: string }
export interface CheckoutInput { email: string; address: Address; shippingMethodId: string; paymentMethod: 'COD' | 'BANK_TRANSFER' | 'STRIPE'; couponCode?: string; items: { variantId: string; quantity: number }[]; idempotencyKey?: string }
export interface Quote { subtotal: number; discount: number; shipping: number; tax: number; total: number; currency: string; items: {variantId: string; name: string; price: number; quantity: number}[] }
export interface ShippingMethod { id: string; name: string; description: string; price: number; freeAbove: number | null; cod: boolean; countries: string[]; active: boolean }
export interface Order { id: string; number: string; email: string; status: string; paymentMethod: string; paymentStatus: string; subtotal: number; discount: number; shipping: number; tax: number; total: number; currency: string; createdAt: string; address: Address; trackingNumber?: string; trackingUrl?: string; items: { id: string; name: string; sku: string; size: string; color: string; quantity: number; price: number; image: string; productId: string }[]; history: { id?: string; status: string; note?: string; createdAt: string }[]; accessToken?: string; paymentUrl?: string }
export interface User { id: string; email: string; name: string; kind: string; permissions: string[]; verified: boolean }
export interface Campaign { id: string; name: string; slug: string; description: string; headline: string; subtitle: string; image: string; mobileImage: string; themeColor: string; textColor: string; ctaText: string; ctaUrl: string; status: string; startsAt: string; endsAt: string; products: Product[]; seoTitle?: string; seoDescription?: string }
export interface Review { id: string; rating: number; title: string; body: string; customerName: string; verified: boolean; reply?: string; createdAt: string }
export interface ApiResponse<T> { success: boolean; data: T; message?: string; errors?: unknown[] }
