import {BadRequestException,Body,Controller,Delete,Get,Inject,Param,Patch,Post,Query,Req,Res,UseGuards} from '@nestjs/common';
import {Response} from 'express';
import {z} from 'zod';
import {AuthGuard,AuthRequest,PermissionGuard,RequirePermission} from '../common/security';
import {ok,parse} from '../common/http';
import {AdminService} from './admin.service';
import {PrismaService} from '../common/prisma.service';
import {ReportsService} from './reports.service';
import {OrdersService} from '../commerce/orders.service';
import {parseCsv,toCsv} from './csv';
import {audit} from '../common/audit';
@Controller('admin') @UseGuards(AuthGuard,PermissionGuard)
export class AdminController {
 constructor(@Inject(AdminService) private admin:AdminService,@Inject(ReportsService) private reports:ReportsService,@Inject(PrismaService) private db:PrismaService,@Inject(OrdersService) private orders:OrdersService){}
 @Get('resources') async resources(@Req() req:AuthRequest){return ok(await this.admin.metadata(req.user!));}
 @Get('dashboard') @RequirePermission('reports.view') async dashboard(){return ok(await this.reports.dashboard());}
 @Get('reports') @RequirePermission('reports.view') async report(){return ok(await this.reports.reports());}
 @Get('search') async search(@Req() req:AuthRequest,@Query('q') q:string){const results:Record<string,unknown>={};for(const key of ['products','orders','customers','campaigns']){try{results[key]=(await this.admin.list(key,{q,pageSize:'5'},req.user!)).items;}catch{results[key]=[];}}return ok(results);}
 @Post('inventory/adjust') @RequirePermission('inventory.edit') async adjust(@Req() req:AuthRequest,@Body() body:unknown){const p=parse(z.object({variantId:z.string(),delta:z.number().int().min(-1000000).max(1000000).refine(v=>v!==0),reason:z.string().min(3).max(500)}).strict(),body);return ok(await this.admin.adjust(p.variantId,p.delta,p.reason,req.user!));}
 @Post('orders/:id/status') @RequirePermission('orders.edit') async status(@Req() req:AuthRequest,@Param('id') id:string,@Body() body:unknown){const p=parse(z.object({status:z.string(),note:z.string().max(1000).default(''),trackingNumber:z.string().max(100).optional(),trackingUrl:z.string().url().startsWith('https://').or(z.literal('')).optional()}).strict(),body);return ok(await this.orders.status(id,p,req.user!.id));}
 @Post('orders/:id/paid') @RequirePermission('orders.edit') async paid(@Req() req:AuthRequest,@Param('id') id:string,@Body() body:unknown){const p=parse(z.object({reference:z.string().min(3).max(200)}),body);return ok(await this.orders.markPaid(id,req.user!.id,p.reference));}
 @Post('orders/:id/refund') @RequirePermission('orders.edit') async refund(@Req() req:AuthRequest,@Param('id') id:string,@Body() body:unknown){const p=parse(z.object({amount:z.number().int().positive(),reason:z.string().min(3).max(1000)}).strict(),body);return ok(await this.orders.refund(id,p.amount,p.reason,req.user!.id));}
 @Post('refunds/:id/complete') @RequirePermission('orders.edit') async completeRefund(@Req() req:AuthRequest,@Param('id') id:string,@Body() body:unknown){const p=parse(z.object({reference:z.string().min(3).max(200)}),body);const refund=await this.db.refund.findUniqueOrThrow({where:{id},include:{order:true}});if(refund.order.paymentMethod==='STRIPE')throw new BadRequestException('Online refunds must be confirmed by the provider');return ok(await this.orders.completeRefund(id,req.user!.id,p.reference));}
 @Post('returns/:id/status') @RequirePermission('orders.edit') async returnStatus(@Req() req:AuthRequest,@Param('id') id:string,@Body() body:unknown){const p=parse(z.object({status:z.string(),note:z.string().max(1000).default('')}),body);return ok(await this.orders.returnStatus(id,p.status,p.note,req.user!.id));}
 @Post('homepage/reorder') @RequirePermission('cms.manage') async reorder(@Req() req:AuthRequest,@Body() body:unknown){return ok(await this.admin.reorder(parse(z.object({ids:z.array(z.string()).max(1000)}),body).ids,req.user!));}
 @Post('products/bulk') async bulk(@Req() req:AuthRequest,@Body() body:unknown){const p=parse(z.object({ids:z.array(z.string()).min(1).max(100),action:z.enum(['activate','archive','delete','assign']),categoryId:z.string().optional(),collectionId:z.string().optional()}).strict(),body);this.admin.resource('products',req.user!,p.action==='delete'?'delete':'edit');if(p.action==='delete'){for(const id of p.ids)await this.admin.remove('products',id,req.user!);}else await this.db.$transaction(async tx=>{await tx.product.updateMany({where:{id:{in:p.ids}},data:{...(p.action==='assign'?{}:{status:p.action==='activate'?'ACTIVE':'ARCHIVED'}),...(p.categoryId?{categoryId:p.categoryId}:{})}});if(p.collectionId)await tx.productCollection.createMany({data:p.ids.map(productId=>({productId,collectionId:p.collectionId!})),skipDuplicates:true});await audit(tx,req.user!.id,`bulk_${p.action}`,'products',p.ids.join(','),undefined,p);});return ok({updated:p.ids.length});}
 @Post('products/import') async importProducts(@Req() req:AuthRequest,@Body() body:unknown){this.admin.resource('products',req.user!,'create');const{csv}=parse(z.object({csv:z.string().max(1000000)}),body);let rows:Record<string,string>[];try{rows=parseCsv(csv);}catch{throw new BadRequestException('Malformed CSV');}if(rows.length>100)throw new BadRequestException('Import at most 100 products per file');const errors:{row:number;message:string}[]=[];let imported=0;for(const [index,row] of rows.entries()){try{const data={...row,price:Number(row.price),salePrice:row.salePrice?Number(row.salePrice):null,tags:row.tags?JSON.parse(row.tags):[],variants:JSON.parse(row.variants||'[]'),images:JSON.parse(row.images||'[]'),collectionIds:row.collectionIds?JSON.parse(row.collectionIds):[]};await this.admin.save('products',undefined,data,req.user!);imported++;}catch(e){errors.push({row:index+2,message:e instanceof Error?e.message:'Invalid row'});}}return ok({imported,errors});}
 @Get('email-preview/:id') @RequirePermission('settings.manage') async emailPreview(@Param('id') id:string){if(process.env.NODE_ENV==='production')throw new BadRequestException('Email preview is disabled in production');return ok(await this.db.emailOutbox.findUniqueOrThrow({where:{id}}));}
 @Get(':resource/export') async export(@Req() req:AuthRequest,@Param('resource') key:string,@Res() res:Response){const r=this.admin.resource(key,req.user!);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${key}.csv"`);let page=1,total=1;while((page-1)*100<total){const data=await this.admin.list(key,{page:String(page),pageSize:'100'},req.user!);total=data.total;const csv=toCsv(data.items as Record<string,unknown>[],r.columns);res.write(page===1?csv: '\r\n'+csv.split('\r\n').slice(1).join('\r\n'));page++;}res.end();}
 @Get(':resource') async list(@Req() req:AuthRequest,@Param('resource') key:string,@Query() q:Record<string,string>){return ok(await this.admin.list(key,q,req.user!));}
 @Get(':resource/:id') async get(@Req() req:AuthRequest,@Param('resource') key:string,@Param('id') id:string){return ok(await this.admin.get(key,id,req.user!));}
 @Post(':resource') async create(@Req() req:AuthRequest,@Param('resource') key:string,@Body() body:unknown){return ok(await this.admin.save(key,undefined,body,req.user!));}
 @Patch(':resource/:id') async update(@Req() req:AuthRequest,@Param('resource') key:string,@Param('id') id:string,@Body() body:unknown){return ok(await this.admin.save(key,id,body,req.user!));}
 @Delete(':resource/:id') async remove(@Req() req:AuthRequest,@Param('resource') key:string,@Param('id') id:string){return ok(await this.admin.remove(key,id,req.user!));}
}
