import {BadRequestException,ForbiddenException,Inject,Injectable,NotFoundException} from '@nestjs/common';
import {Prisma} from '@prisma/client';
import bcrypt from 'bcryptjs';
import {PrismaService} from '../common/prisma.service';
import {Principal} from '../common/security';
import {audit} from '../common/audit';
import {paging,paginated,parse} from '../common/http';
import {ContentService} from '../content/content.service';
import {orderInclude,orderView} from '../commerce/order-view';
import {productInclude,serializeProduct} from '../catalog/catalog.service';
import {allowedPermissions,Resource,resources,productSchema} from './resources';
import {ProductsAdminService} from './products.service';
type Row=Record<string,unknown> & {id:string};
// Runtime delegate lookup is constrained to the registry. Every write is parsed by its strict resource schema.
interface Delegate {findMany(args:Record<string,unknown>):Promise<Row[]>;count(args:Record<string,unknown>):Promise<number>;findUniqueOrThrow(args:Record<string,unknown>):Promise<Row>;create(args:Record<string,unknown>):Promise<Row>;update(args:Record<string,unknown>):Promise<Row>;delete(args:Record<string,unknown>):Promise<Row>}
const editOnly=new Set(['reviews','inquiries','notifications']);
const jsonFields=new Set(['rules','sizeGuide','attributes']);
@Injectable()
export class AdminService {
 constructor(@Inject(PrismaService) private db:PrismaService,@Inject(ContentService) private content:ContentService,@Inject(ProductsAdminService) private products:ProductsAdminService){}
 allowed(user:Principal,permission:string){return user.permissions.includes('*')||user.permissions.includes(permission);}
 private canDelegate(user:Principal,permissions:string[]){return user.permissions.includes('*')||permissions.every(p=>p!=='*'&&user.permissions.includes(p));}
 resource(key:string,user:Principal,operation:'read'|'create'|'edit'|'delete'='read'){const r=resources.find(r=>r.key===key);if(!r)throw new NotFoundException('Resource not found');const permission=operation==='read'?r.permission:key==='products'?`products.${operation==='edit'?'edit':operation}`:r.writePermission||r.permission;if(!this.allowed(user,permission))throw new ForbiddenException('You do not have permission for this action');if(operation!=='read'&&(r.readOnly||(editOnly.has(key)&&operation!=='edit')))throw new BadRequestException('Use the dedicated workflow for this resource');return r;}
 private delegate(db:PrismaService|Prisma.TransactionClient,r:Resource){return (db as unknown as Record<string,Delegate>)[r.model];}
 async metadata(user:Principal){const[categories,roles,campaigns]=await Promise.all([this.db.category.findMany({select:{id:true,name:true},take:100}),this.allowed(user,'users.manage')?this.db.role.findMany():[],this.db.campaign.findMany({select:{id:true,name:true},take:100})]);const options=(rows:{id:string;name:string}[])=>rows.map(r=>({value:r.id,label:r.name}));return resources.filter(r=>this.allowed(user,r.permission)).map(({model,schema,search,writePermission,...r})=>({...r,canCreate:!r.readOnly&&!editOnly.has(r.key)&&this.allowed(user,r.key==='products'?'products.create':writePermission||r.permission),canEdit:!r.readOnly&&this.allowed(user,r.key==='products'?'products.edit':writePermission||r.permission),canDelete:!r.readOnly&&!editOnly.has(r.key)&&this.allowed(user,r.key==='products'?'products.delete':writePermission||r.permission),fields:r.fields.map(f=>({...f,required:['name','slug','sku','categoryId','price','code','key','title','email'].includes(f.name),...(f.name==='categoryId'||f.name==='parentId'?{options:options(categories)}:f.name==='roleId'?{options:options(roles)}:f.name==='campaignId'?{options:options(campaigns)}:{})}))}));}
 async list(key:string,q:Record<string,string>,user:Principal){const r=this.resource(key,user),p=paging(q);const where:Record<string,unknown>={};if(q.q&&r.search.length)where.OR=r.search.map(name=>({[name]:{contains:q.q.slice(0,100),mode:'insensitive'}}));if(key==='users')where.kind='ADMIN';if(key==='customers')where.kind='CUSTOMER';if(key==='abandoned-carts')where.updatedAt={lt:new Date(Date.now()-3600000)};
  if(key==='inventory'){const iw=q.q?{variant:{OR:[{sku:{contains:q.q,mode:'insensitive' as const}},{product:{name:{contains:q.q,mode:'insensitive' as const}}}]}}:{};const[rows,total]=await Promise.all([this.db.inventory.findMany({where:iw,include:{variant:{include:{product:true}},warehouse:true},skip:p.skip,take:p.take,orderBy:{updatedAt:'desc'}}),this.db.inventory.count({where:iw})]);return paginated(rows.map(i=>({id:i.id,variantId:i.variantId,sku:i.variant.sku,productName:i.variant.product.name,color:i.variant.color,size:i.variant.size,quantity:i.quantity,reserved:i.reserved,available:i.quantity-i.reserved,warehouse:i.warehouse.name,lowStockThreshold:i.variant.lowStockThreshold})),total,p.page,p.pageSize);}
  const include=key==='products'?productInclude:key==='orders'?orderInclude:undefined;
  const orderBy=key==='homepage'?{position:'asc'}:key==='pages'?{updatedAt:'desc'}:['category','collection','menu','role','siteSetting','shippingMethod','taxRule','coupon','discount','campaign','emailTemplate'].includes(r.model)?{id:'desc'}:{createdAt:'desc'};
  if(key==='abandoned-carts')Object.assign(orderBy,{updatedAt:'desc'});
  const delegate=this.delegate(this.db,r);const[items,total]=await Promise.all([delegate.findMany({where,...(include?{include}:{}),skip:p.skip,take:p.take,orderBy:key==='abandoned-carts'?{updatedAt:'desc'}:orderBy}),delegate.count({where})]);return paginated(items.map(item=>this.clean(key,item)),total,p.page,p.pageSize);
 }
 private clean(key:string,row:Row):Row{if(key==='orders')return orderView(row as unknown as Parameters<typeof orderView>[0],true) as unknown as Row;if(key==='products'){const p=row as unknown as Parameters<typeof serializeProduct>[0];return{...serializeProduct(p),costPrice:p.costPrice,collectionIds:p.collections.map(c=>c.collectionId)} as unknown as Row;}const{passwordHash,tokenHash,accessTokenHash,requestHash,idempotencyKey,...safe}=row;return safe as Row;}
 async get(key:string,id:string,user:Principal){const r=this.resource(key,user);if(key==='products')return this.products.get(id);if(key==='orders')return orderView(await this.db.order.findUniqueOrThrow({where:{id},include:orderInclude}),true);if(key==='inventory'){const row=await this.db.inventory.findUniqueOrThrow({where:{id},include:{variant:{include:{product:true}},warehouse:true}});return{id:row.id,variantId:row.variantId,sku:row.variant.sku,productName:row.variant.product.name,color:row.variant.color,size:row.variant.size,quantity:row.quantity,reserved:row.reserved,available:row.quantity-row.reserved,warehouse:row.warehouse.name};}
  const include=key==='campaigns'?{products:true}:key==='collections'?{products:true}:key==='returns'?{items:{include:{orderItem:true}},order:{select:{number:true}}}:key==='customers'?{addresses:true,orders:{take:20,orderBy:{createdAt:'desc'},include:orderInclude}}:undefined;
  const row=await this.delegate(this.db,r).findUniqueOrThrow({where:{id},...(include?{include}:{})});if(key==='users'&&row.kind!=='ADMIN'||key==='customers'&&row.kind!=='CUSTOMER')throw new NotFoundException();if(key==='campaigns'||key==='collections')row.productIds=(row.products as {productId:string}[]).map(p=>p.productId);if(key==='customers')row.orders=(row.orders as Parameters<typeof orderView>[0][]).map(order=>orderView(order,true));return this.clean(key,row);
 }
 async save(key:string,id:string|undefined,body:unknown,user:Principal){const r=this.resource(key,user,id?'edit':'create');if(key==='products')return this.products.save(id,parse(productSchema,body),user.id);const value=parse(r.schema,body) as Record<string,unknown>;
  for(const k of ['parentId','campaignId'])if(value[k]==='')value[k]=null;
  if(value.startsAt&&value.endsAt&&new Date(String(value.startsAt))>=new Date(String(value.endsAt)))throw new BadRequestException('End date must follow start date');if(value.type==='PERCENTAGE'&&Number(value.value)>100)throw new BadRequestException('Percentage must not exceed 100');if(key==='coupons'&&value.type==='BUY_X_GET_Y'&&(!value.buyQuantity||!value.getQuantity))throw new BadRequestException('Buy and get quantities must be positive');
  if(key==='roles'){const permissions=value.permissions as string[];if(permissions.some(p=>p!=='*'&&!allowedPermissions.includes(p)))throw new BadRequestException('Unknown permission');const previous=id?await this.db.role.findUnique({where:{id}}):null;if(!this.canDelegate(user,permissions)||(previous&&!this.canDelegate(user,previous.permissions)))throw new ForbiddenException('You cannot grant or modify permissions beyond your own role');}
  if(key==='users'){if(!id&&!value.password)throw new BadRequestException('A password is required for a new administrator');const role=await this.db.role.findUniqueOrThrow({where:{id:String(value.roleId)}});const previous=id?await this.db.user.findUniqueOrThrow({where:{id},include:{role:true}}):null;if(!this.canDelegate(user,role.permissions)||(previous?.role&&!this.canDelegate(user,previous.role.permissions)))throw new ForbiddenException('You cannot assign or modify a more privileged role');if(previous&&previous.kind!=='ADMIN')throw new BadRequestException('Customer accounts cannot be promoted through this editor');if(value.password)value.passwordHash=await bcrypt.hash(String(value.password),12);delete value.password;value.kind='ADMIN';if(id===user.id&&(value.active===false||previous?.roleId!==value.roleId))throw new BadRequestException('You cannot disable your own account or change your own role');}
  if(key==='categories'&&id&&value.parentId===id)throw new BadRequestException('A category cannot be its own parent');for(const field of jsonFields)if(value[field]===null)value[field]=Prisma.DbNull;
  const result=await this.db.$transaction(async tx=>{const d=this.delegate(tx,r);const before=id?await d.findUniqueOrThrow({where:{id}}):undefined;const{productIds,...data}=value;const row=id?await d.update({where:{id},data}):await d.create({data});if(key==='campaigns'){await tx.campaignProduct.deleteMany({where:{campaignId:row.id}});if(Array.isArray(productIds)&&productIds.length)await tx.campaignProduct.createMany({data:productIds.map(productId=>({campaignId:row.id,productId:String(productId)})),skipDuplicates:true});}if(key==='collections'){await tx.productCollection.deleteMany({where:{collectionId:row.id}});if(Array.isArray(productIds)&&productIds.length)await tx.productCollection.createMany({data:productIds.map(productId=>({collectionId:row.id,productId:String(productId)})),skipDuplicates:true});}await audit(tx,user.id,id?'updated':'created',key,row.id,before,value);return row;});await this.content.invalidate();return this.clean(key,result);
 }
 async remove(key:string,id:string,user:Principal){const r=this.resource(key,user,'delete');if(key==='products')return this.products.remove(id,user.id);if(key==='users'&&id===user.id)throw new BadRequestException('You cannot delete your own account');if(key==='roles'&&await this.db.user.count({where:{roleId:id}}))throw new BadRequestException('This role is assigned to users');const result=await this.db.$transaction(async tx=>{if(key==='users'){const target=await tx.user.findUniqueOrThrow({where:{id},include:{role:true}});if(target.kind!=='ADMIN')throw new NotFoundException('Administrator not found');if(target.role&&!this.canDelegate(user,target.role.permissions))throw new ForbiddenException('You cannot delete a more privileged administrator');}if(key==='roles'){const target=await tx.role.findUniqueOrThrow({where:{id}});if(!this.canDelegate(user,target.permissions))throw new ForbiddenException('You cannot delete a more privileged role');}const row=await this.delegate(tx,r).delete({where:{id}});await audit(tx,user.id,'deleted',key,id,row);return{deleted:true};});await this.content.invalidate();return result;}
 async adjust(variantId:string,delta:number,reason:string,user:Principal){if(!this.allowed(user,'inventory.edit'))throw new ForbiddenException();return this.db.$transaction(async tx=>{const inventory=await tx.inventory.findFirst({where:{variantId},orderBy:{id:'asc'}});const warehouse=inventory?{id:inventory.warehouseId}:await tx.warehouse.findFirstOrThrow();if((inventory?.quantity||0)+delta<(inventory?.reserved||0))throw new BadRequestException('Adjustment would make available stock negative');const result=await tx.inventory.upsert({where:{variantId_warehouseId:{variantId,warehouseId:warehouse.id}},create:{variantId,warehouseId:warehouse.id,quantity:delta},update:{quantity:{increment:delta}}});await tx.inventoryTransaction.create({data:{variantId,warehouseId:warehouse.id,delta,type:delta>0?'STOCK_IN':'MANUAL_ADJUSTMENT',reason}});await audit(tx,user.id,'adjusted','inventory',result.id,inventory,{delta,reason});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async reorder(ids:string[],user:Principal){this.resource('homepage',user,'edit');if(new Set(ids).size!==ids.length)throw new BadRequestException('Duplicate sections');const all=await this.db.homepageSection.findMany({orderBy:{position:'asc'},select:{id:true}});if(ids.some(id=>!all.some(s=>s.id===id)))throw new BadRequestException('Unknown section');const ordered=[...ids,...all.map(s=>s.id).filter(id=>!ids.includes(id))];await this.db.$transaction(async tx=>{for(const [position,id] of ordered.entries())await tx.homepageSection.update({where:{id},data:{position}});await audit(tx,user.id,'reordered','homepage','all',all,ordered);});await this.content.invalidate();return{saved:true};}
}
