import {Inject,Injectable} from '@nestjs/common';
import {PrismaService} from '../common/prisma.service';
import {orderInclude,orderView} from '../commerce/order-view';
@Injectable()
export class ReportsService {
 constructor(@Inject(PrismaService) private db:PrismaService){}
 async dashboard(){const today=new Date();today.setHours(0,0,0,0);const paid={paymentStatus:{in:['PAID','PARTIALLY_REFUNDED','REFUNDED']}};const[total,todayTotal,totalOrders,todayOrders,totalCustomers,lowStock,pendingOrders,returns,refunds,recent,sales,topProducts]=await Promise.all([
  this.db.order.aggregate({where:paid,_sum:{total:true},_count:true}),this.db.order.aggregate({where:{...paid,createdAt:{gte:today}},_sum:{total:true}}),this.db.order.count(),this.db.order.count({where:{createdAt:{gte:today}}}),this.db.user.count({where:{kind:'CUSTOMER'}}),this.db.$queryRaw<{count:bigint}[]>`SELECT COUNT(*) AS count FROM "Inventory" i JOIN "ProductVariant" v ON v.id=i."variantId" WHERE i.quantity-i.reserved <= v."lowStockThreshold"`,this.db.order.count({where:{status:'PENDING'}}),this.db.returnRequest.count({where:{status:{in:['REQUESTED','APPROVED','RECEIVED']}}}),this.db.refund.aggregate({where:{status:'COMPLETED'},_sum:{amount:true}}),this.db.order.findMany({take:8,orderBy:{createdAt:'desc'},include:orderInclude}),
  this.db.$queryRaw<{date:string;revenue:bigint;orders:bigint}[]>`SELECT to_char("createdAt",'YYYY-MM-DD') AS date, SUM(total)::bigint AS revenue, COUNT(*)::bigint AS orders FROM "Order" WHERE "paymentStatus" IN ('PAID','PARTIALLY_REFUNDED','REFUNDED') AND "createdAt">NOW()-INTERVAL '30 days' GROUP BY 1 ORDER BY 1`,
  this.db.$queryRaw<{name:string;units:bigint;revenue:bigint}[]>`SELECT i.name,SUM(i.quantity)::bigint AS units,SUM(i.price::bigint*i.quantity)::bigint AS revenue FROM "OrderItem" i JOIN "Order" o ON o.id=i."orderId" WHERE o."paymentStatus" IN ('PAID','PARTIALLY_REFUNDED','REFUNDED') GROUP BY i."productId",i.name ORDER BY revenue DESC LIMIT 8`
 ]);const revenue=Number(total._sum.total||0)-Number(refunds._sum.amount||0);return{revenue,todayRevenue:todayTotal._sum.total||0,totalOrders,todayOrders,totalCustomers,averageOrderValue:total._count?Math.round((total._sum.total||0)/total._count):0,lowStock:Number(lowStock[0]?.count||0),pendingOrders,returns,refunds:refunds._sum.amount||0,recentOrders:recent.map(order=>orderView(order,true)),sales:sales.map(s=>({...s,revenue:Number(s.revenue),orders:Number(s.orders)})),topProducts:topProducts.map(s=>({...s,revenue:Number(s.revenue),units:Number(s.units)}))};}
 async reports(){const[dashboard,categories,collections,coupons,newCustomers,returning]=await Promise.all([this.dashboard(),
 this.db.$queryRaw<{name:string;revenue:bigint;units:bigint}[]>`SELECT c.name,SUM(i.price::bigint*i.quantity)::bigint AS revenue,SUM(i.quantity)::bigint AS units FROM "OrderItem" i JOIN "Order" o ON o.id=i."orderId" JOIN "Product" p ON p.id=i."productId" JOIN "Category" c ON c.id=p."categoryId" WHERE o."paymentStatus" IN ('PAID','PARTIALLY_REFUNDED','REFUNDED') GROUP BY c.id,c.name ORDER BY revenue DESC LIMIT 30`,
 this.db.$queryRaw<{name:string;revenue:bigint;units:bigint}[]>`SELECT c.name,SUM(i.price::bigint*i.quantity)::bigint AS revenue,SUM(i.quantity)::bigint AS units FROM "OrderItem" i JOIN "Order" o ON o.id=i."orderId" JOIN "ProductCollection" pc ON pc."productId"=i."productId" JOIN "Collection" c ON c.id=pc."collectionId" WHERE o."paymentStatus" IN ('PAID','PARTIALLY_REFUNDED','REFUNDED') GROUP BY c.id,c.name ORDER BY revenue DESC LIMIT 30`,
 this.db.$queryRaw<{code:string;uses:bigint;discount:bigint}[]>`SELECT c.code,COUNT(o.id)::bigint AS uses,COALESCE(SUM(o.discount),0)::bigint AS discount FROM "Coupon" c LEFT JOIN "Order" o ON o."couponId"=c.id AND o.status<>'CANCELLED' GROUP BY c.id,c.code ORDER BY uses DESC LIMIT 100`,this.db.user.count({where:{kind:'CUSTOMER',createdAt:{gte:new Date(Date.now()-30*86400000)}}}),this.db.$queryRaw<{count:bigint}[]>`SELECT COUNT(*) AS count FROM (SELECT email FROM "Order" WHERE status<>'CANCELLED' GROUP BY email HAVING COUNT(*)>1) customers`
 ]);const amounts=(rows:{name:string;revenue:bigint;units:bigint}[])=>rows.map(r=>({...r,revenue:Number(r.revenue),units:Number(r.units)}));return{...dashboard,categories:amounts(categories),collections:amounts(collections),coupons:coupons.map(c=>({...c,uses:Number(c.uses),discount:Number(c.discount)})),customers:{new:newCustomers,returning:Number(returning[0]?.count||0)}};}
}
