import {z} from 'zod';
import {passwordSchema} from '@vanta/validation';
export type Field={name:string;label:string;type:string;required?:boolean;options?:string[]|{label:string;value:string}[];default?:unknown};
export type Resource={key:string;label:string;model:string;permission:string;writePermission?:string;readOnly?:boolean;search:string[];fields:Field[];columns:string[];schema:z.ZodObject<z.ZodRawShape>};
const text=z.string().trim().max(500);const long=z.string().max(10000);const name=text.min(1);const slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(150);const nonnegative=z.number().int().min(0).max(2000000000);const strings=z.array(text).max(200).default([]);const date=z.coerce.date().nullable().optional();
export const safeUrl=z.string().max(2000).refine(v=>v===''||(/^\/(?!\/)/.test(v))||/^https?:\/\//.test(v),'Use a relative path or http(s) URL');
function jsonSafe(v:unknown,depth=0):boolean{if(depth>10)return false;if(!v||typeof v!=='object')return true;return Object.entries(v).every(([k,value])=>!['__proto__','constructor','prototype','html','script'].includes(k)&&(!/(href|url)$/i.test(k)||typeof value!=='string'||safeUrl.safeParse(value).success)&&jsonSafe(value,depth+1));}
export const safeJson=z.json().refine(v=>JSON.stringify(v).length<100000&&jsonSafe(v),'Content contains unsafe links or exceeds limits');
const f=(name:string,type='text',def?:unknown,options?:string[]):Field=>({name,label:name.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()),type,...(def!==undefined?{default:def}:{}),...(options?{options}:{})});
const seo={seoTitle:text.default(''),seoDescription:text.default('')};const seoFields=[f('seoTitle'),f('seoDescription','textarea')];
const imageSchema=z.object({url:safeUrl.refine(v=>v.length>0),alt:text,position:nonnegative.default(0)});
export const variantSchema=z.object({id:text.optional(),sku:name,color:name,colorHex:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#161616'),size:name,price:nonnegative.nullable().optional(),salePrice:nonnegative.nullable().optional(),stock:nonnegative.default(0),active:z.boolean().default(true),barcode:text.default(''),weight:nonnegative.default(300),image:safeUrl.default(''),lowStockThreshold:nonnegative.default(5)});
export const productSchema=z.object({name,slug,sku:name,description:long.default(''),shortDescription:text.default(''),price:nonnegative,salePrice:nonnegative.nullable().optional(),costPrice:nonnegative.default(0),categoryId:name,gender:z.enum(['MEN','WOMEN','UNISEX']).default('UNISEX'),tags:strings,status:z.enum(['DRAFT','ACTIVE','ARCHIVED']).default('DRAFT'),visibility:z.boolean().default(true),featured:z.boolean().default(false),isNew:z.boolean().default(false),bestSeller:z.boolean().default(false),material:text.default(''),fit:text.default(''),care:long.default(''),modelInfo:text.default(''),shippingInfo:text.default(''),returnInfo:text.default(''),sizeGuide:safeJson.nullable().optional(),attributes:safeJson.nullable().optional(),taxClass:text.default('standard'),video:safeUrl.default(''),...seo,ogImage:safeUrl.default(''),canonicalUrl:safeUrl.default(''),noindex:z.boolean().default(false),images:z.array(imageSchema).max(30).default([]),variants:z.array(variantSchema).min(1).max(200),collectionIds:strings}).strict();
const scope={productIds:strings,categoryIds:strings,collectionIds:strings};const scopeFields=[f('productIds','json',[]),f('categoryIds','json',[]),f('collectionIds','json',[])];
const couponSchema=z.object({code:z.string().trim().min(1).max(60).transform(v=>v.toUpperCase()),name,description:long.default(''),type:z.enum(['PERCENTAGE','FIXED','FREE_SHIPPING','BUY_X_GET_Y']),value:nonnegative,minOrder:nonnegative.default(0),maxDiscount:nonnegative.nullable().optional(),startsAt:date,endsAt:date,usageLimit:nonnegative.nullable().optional(),perCustomerLimit:z.number().int().min(1).max(10000).default(1),firstOrderOnly:z.boolean().default(false),active:z.boolean().default(true),...scope,excludedProductIds:strings,customerEmails:z.array(z.email()).default([]),buyQuantity:nonnegative.default(0),getQuantity:nonnegative.default(0)}).strict();
function resource(key:string,label:string,model:string,permission:string,schema:z.ZodObject<z.ZodRawShape>,fields:Field[],columns:string[],search:string[]=[],writePermission?:string):Resource{return{key,label,model,permission,schema,fields,columns,search,writePermission};}
const read=(key:string,label:string,model:string,permission:string,columns:string[],search:string[]=[]):Resource=>({...resource(key,label,model,permission,z.object({}).strict(),[],columns,search),readOnly:true});
export const resources:Resource[]=[
 resource('products','Products','product','products.view',productSchema,[f('name'),f('slug'),f('sku'),f('categoryId','select'),f('gender','select','UNISEX',['MEN','WOMEN','UNISEX']),f('description','textarea'),f('shortDescription','textarea'),f('price','number',0),f('salePrice','number'),f('costPrice','number',0),f('status','select','DRAFT',['DRAFT','ACTIVE','ARCHIVED']),f('visibility','boolean',true),f('featured','boolean',false),f('isNew','boolean',false),f('bestSeller','boolean',false),f('tags','json',[]),f('material'),f('fit'),f('care','textarea'),f('sizeGuide','json',null),f('attributes','json',null),f('taxClass','text','standard'),f('modelInfo'),f('shippingInfo'),f('returnInfo'),f('video'),...seoFields,f('ogImage'),f('canonicalUrl'),f('noindex','boolean',false)],['name','sku','status','price'],['name','sku'],'products.edit'),
 resource('categories','Categories','category','products.view',z.object({name,slug,description:long.default(''),image:safeUrl.default(''),parentId:text.nullable().optional(),position:nonnegative.default(0),active:z.boolean().default(true),...seo}).strict(),[f('name'),f('slug'),f('description','textarea'),f('image'),f('parentId','select'),f('position','number',0),f('active','boolean',true),...seoFields],['name','slug','active'],['name'],'products.edit'),
 resource('collections','Collections','collection','products.view',z.object({name,slug,description:long.default(''),image:safeUrl.default(''),active:z.boolean().default(true),rules:safeJson.nullable().optional(),...seo,productIds:strings}).strict(),[f('name'),f('slug'),f('description','textarea'),f('image'),f('active','boolean',true),f('rules','json',null),f('productIds','json',[]),...seoFields],['name','slug','active'],['name'],'products.edit'),
 resource('campaigns','Campaigns','campaign','campaigns.manage',z.object({name,slug,description:long.default(''),headline:name,subtitle:text.default(''),image:safeUrl.default(''),mobileImage:safeUrl.default(''),themeColor:z.string().regex(/^#[a-fA-F0-9]{6}$/),textColor:z.string().regex(/^#[a-fA-F0-9]{6}$/),ctaText:text.default('SHOP THE DROP'),ctaUrl:safeUrl.default('/shop'),status:z.enum(['DRAFT','SCHEDULED','ACTIVE','ARCHIVED']),startsAt:z.coerce.date(),endsAt:z.coerce.date(),productIds:strings,...seo}).strict(),[f('name'),f('slug'),f('headline'),f('subtitle'),f('description','textarea'),f('image'),f('mobileImage'),f('themeColor','text','#d8ff00'),f('textColor','text','#000000'),f('ctaText','text','SHOP THE DROP'),f('ctaUrl','text','/shop'),f('status','select','DRAFT',['DRAFT','SCHEDULED','ACTIVE','ARCHIVED']),f('startsAt','datetime'),f('endsAt','datetime'),f('productIds','json',[]),...seoFields],['name','status','startsAt','endsAt'],['name','slug']),
 resource('coupons','Coupons','coupon','campaigns.manage',couponSchema,[f('code'),f('name'),f('description','textarea'),f('type','select','PERCENTAGE',['PERCENTAGE','FIXED','FREE_SHIPPING','BUY_X_GET_Y']),f('value','number',10),f('minOrder','number',0),f('maxDiscount','number'),f('startsAt','datetime'),f('endsAt','datetime'),f('usageLimit','number'),f('perCustomerLimit','number',1),f('firstOrderOnly','boolean',false),f('active','boolean',true),...scopeFields,f('excludedProductIds','json',[]),f('customerEmails','json',[]),f('buyQuantity','number',0),f('getQuantity','number',0)],['code','type','value','usedCount','active'],['code','name']),
 resource('discounts','Discounts','discount','campaigns.manage',z.object({name,type:z.enum(['PERCENTAGE','FIXED']),value:nonnegative,...scope,startsAt:date,endsAt:date,active:z.boolean().default(true),campaignId:text.nullable().optional()}).strict(),[f('name'),f('type','select','PERCENTAGE',['PERCENTAGE','FIXED']),f('value','number',10),...scopeFields,f('startsAt','datetime'),f('endsAt','datetime'),f('campaignId','select'),f('active','boolean',true)],['name','type','value','active'],['name']),
 resource('homepage','Homepage sections','homepageSection','cms.manage',z.object({type:z.enum(['hero','products','categories','editorial','campaign','newsletter','shop-the-look','announcement','custom','video']),title:text.default(''),subtitle:long.default(''),config:safeJson,position:nonnegative.default(0),enabled:z.boolean().default(true),startsAt:date,endsAt:date,campaignId:text.nullable().optional()}).strict(),[f('type','select','hero',['hero','products','categories','editorial','campaign','newsletter','shop-the-look','announcement','custom','video']),f('title'),f('subtitle','textarea'),f('position','number',0),f('enabled','boolean',true),f('startsAt','datetime'),f('endsAt','datetime'),f('campaignId','select'),f('config','json',{})],['position','type','title','enabled'],['title']),
 resource('pages','Pages','page','cms.manage',z.object({title:name,slug,body:safeJson,status:z.enum(['DRAFT','PUBLISHED']),...seo,ogImage:safeUrl.default(''),noindex:z.boolean().default(false)}).strict(),[f('title'),f('slug'),f('status','select','DRAFT',['DRAFT','PUBLISHED']),f('body','json',[]),...seoFields,f('ogImage'),f('noindex','boolean',false)],['title','slug','status'],['title']),
 resource('menus','Menus','menu','cms.manage',z.object({name,items:safeJson}).strict(),[f('name'),f('items','json',[])],['name'],['name']),
 resource('shipping','Shipping methods','shippingMethod','settings.manage',z.object({name,description:text.default(''),price:nonnegative,freeAbove:nonnegative.nullable().optional(),countries:z.array(z.string().length(2)).min(1),cities:strings,minWeight:nonnegative.default(0),maxWeight:nonnegative.nullable().optional(),minOrder:nonnegative.default(0),maxOrder:nonnegative.nullable().optional(),cod:z.boolean().default(true),active:z.boolean().default(true)}).strict(),[f('name'),f('description'),f('price','number',25000),f('freeAbove','number',500000),f('countries','json',['PK']),f('cities','json',[]),f('minWeight','number',0),f('maxWeight','number'),f('minOrder','number',0),f('maxOrder','number'),f('cod','boolean',true),f('active','boolean',true)],['name','price','freeAbove','active'],['name']),
 resource('taxes','Tax rules','taxRule','settings.manage',z.object({name,country:z.string().length(2),taxClass:text.default('standard'),rate:nonnegative.max(10000),included:z.boolean().default(false),active:z.boolean().default(true)}).strict(),[f('name'),f('country','text','PK'),f('taxClass','text','standard'),f('rate','number',0),f('included','boolean',false),f('active','boolean',true)],['name','country','rate','included'],['name']),
 resource('settings','Site settings','siteSetting','settings.manage',z.object({key:name.regex(/^[a-zA-Z][a-zA-Z0-9]*$/),value:safeJson}).strict(),[f('key'),f('value','json','')],['key','value'],['key']),
 resource('roles','Roles','role','users.manage',z.object({name,permissions:strings}).strict(),[f('name'),f('permissions','json',[])],['name','permissions'],['name']),
 resource('users','Admin users','user','users.manage',z.object({name,email:z.email().transform(v=>v.toLowerCase()),password:passwordSchema.optional(),roleId:name,active:z.boolean().default(true)}).strict(),[f('name'),f('email'),f('password','password'),f('roleId','select'),f('active','boolean',true)],['name','email','active'],['name','email']),
 resource('reviews','Reviews','review','cms.manage',z.object({status:z.enum(['PENDING','APPROVED','REJECTED']),reply:long.default('')}).strict(),[f('status','select','PENDING',['PENDING','APPROVED','REJECTED']),f('reply','textarea')],['customerName','rating','title','status'],['title','customerName']),
 resource('media','Media library','media','cms.manage',z.object({name,url:safeUrl.refine(v=>/^https?:/.test(v)),alt:text.default(''),mime:z.enum(['image/jpeg','image/png','image/webp','image/avif','video/mp4','video/webm'])}).strict(),[f('name'),f('url'),f('alt'),f('mime','select','image/jpeg',['image/jpeg','image/png','image/webp','image/avif','video/mp4','video/webm'])],['name','mime','alt','size'],['name','alt']),
 resource('email-templates','Email templates','emailTemplate','settings.manage',z.object({key:name,subject:name,body:long}).strict(),[f('key'),f('subject'),f('body','textarea')],['key','subject'],['key','subject']),
 resource('inquiries','Inquiries','inquiry','customers.view',z.object({status:z.enum(['OPEN','IN_PROGRESS','CLOSED'])}).strict(),[f('status','select','OPEN',['OPEN','IN_PROGRESS','CLOSED'])],['name','email','subject','status'],['email','subject']),
 resource('notifications','Notifications','notification','orders.view',z.object({read:z.boolean()}).strict(),[f('read','boolean',true)],['title','body','read','createdAt'],['title']),
 read('customers','Customers','user','customers.view',['name','email','verified','createdAt'],['name','email']),
 read('orders','Orders','order','orders.view',['number','email','total','paymentStatus','status','createdAt'],['number','email']),
 read('inventory','Inventory','inventory','inventory.edit',['productName','sku','color','size','quantity','reserved','available'],[]),
 read('audit-logs','Audit logs','auditLog','users.manage',['action','entity','entityId','createdAt'],['action','entity']),
 read('returns','Returns','returnRequest','orders.view',['id','orderId','reason','status','createdAt'],['reason']),
 read('refunds','Refunds','refund','orders.view',['id','orderId','amount','status','reason'],['reason']),
 read('payments','Payments','payment','orders.view',['id','orderId','provider','status','amount'],['provider']),
 read('newsletter','Newsletter','newsletterSubscriber','campaigns.manage',['email','source','active','createdAt'],['email']),
 read('abandoned-carts','Abandoned carts','cart','customers.view',['email','updatedAt'],['email'])
];
export const allowedPermissions=['products.view','products.create','products.edit','products.delete','inventory.edit','orders.view','orders.edit','customers.view','campaigns.manage','cms.manage','users.manage','settings.manage','reports.view'];
